export interface Tool {
  name: string;
  slug: string;
  description: string;
  category: string;
  icon: string;
  keywords: string[];
}

export interface Category {
  name: string;
  slug: string;
  icon: string;
  description: string;
  color: string;
}

export const categories: Category[] = [
  { name: "Finance Calculators", slug: "finance", icon: "💰", description: "EMI, SIP, FD, RD, PPF, Loan & Investment calculators", color: "from-emerald-400 to-teal-500" },
  { name: "Math & Numbers", slug: "math", icon: "🔢", description: "Percentage, Age, BMI, Unit converters & more", color: "from-blue-400 to-indigo-500" },
  { name: "Text Tools", slug: "text", icon: "📝", description: "Word counter, Case converter, Lorem Ipsum & text utilities", color: "from-violet-400 to-purple-500" },
  { name: "Converter Tools", slug: "converters", icon: "🔄", description: "Unit, Currency, Temperature, Length & data converters", color: "from-orange-400 to-red-500" },
  { name: "Developer Tools", slug: "developer", icon: "💻", description: "JSON formatter, Base64, Hash generator, Regex tester", color: "from-cyan-400 to-blue-500" },
  { name: "Image Tools", slug: "image", icon: "🖼️", description: "Compress, Resize, Crop, Convert image formats", color: "from-pink-400 to-rose-500" },
  { name: "SEO Tools", slug: "seo", icon: "🔍", description: "Meta tag generator, Sitemap, Robots.txt & SEO utilities", color: "from-amber-400 to-yellow-500" },
  { name: "Date & Time", slug: "datetime", icon: "📅", description: "Date calculator, Countdown, Timezone converter & more", color: "from-lime-400 to-green-500" },
  { name: "Security & Privacy", slug: "security", icon: "🔒", description: "Password generator, Privacy policy, Terms generator & more", color: "from-red-400 to-pink-500" },
  { name: "Health & Fitness", slug: "health", icon: "❤️", description: "BMR, Calorie, Pregnancy calculator & health tools", color: "from-rose-400 to-red-500" },
  { name: "Tax & Salary", slug: "tax", icon: "🧾", description: "HRA, TDS, EPF, NPS, Stamp duty & tax calculators for India", color: "from-teal-400 to-cyan-500" },
  { name: "Fun & Utility", slug: "fun", icon: "🎮", description: "Love calculator, Flip coin, Roll dice, Typing test & more", color: "from-fuchsia-400 to-pink-500" },
  { name: "CSS & Design", slug: "css", icon: "🎨", description: "Gradient, Box shadow, Border radius & CSS generators", color: "from-sky-400 to-indigo-500" },
  { name: "Data Tools", slug: "data", icon: "📊", description: "JSON to CSV, CSV to JSON, Text diff & data converters", color: "from-yellow-400 to-amber-500" },
  { name: "Social Media", slug: "social", icon: "📱", description: "Instagram bio, hashtags, image resizer & social media utilities", color: "from-pink-400 to-fuchsia-500" },
  { name: "Education", slug: "education", icon: "🎓", description: "GPA, CGPA, grade calculator, study planner & academic tools", color: "from-indigo-400 to-violet-500" },
  { name: "Business", slug: "business", icon: "💼", description: "GST invoice, profit/loss, ROI, break-even & business calculators", color: "from-emerald-400 to-green-500" },
  { name: "PDF Tools", slug: "pdf", icon: "📄", description: "Convert, merge, split, compress & manipulate PDF files", color: "from-red-400 to-orange-500" },
  { name: "Everyday Utility", slug: "utility", icon: "🔧", description: "Vehicle info, IFSC, PIN code, PAN, Aadhaar, GST validators & more", color: "from-slate-400 to-zinc-500" },
  { name: "Real Estate", slug: "realestate", icon: "🏠", description: "Plot area, paint, tile, brick, cement & interior cost calculators", color: "from-stone-400 to-amber-500" },
  { name: "Electrical & Engineering", slug: "electrical", icon: "⚡", description: "Wire size, voltage drop, power consumption, Ohm's law, transformer & solar calculators", color: "from-yellow-400 to-orange-500" },
  { name: "Cooking & Kitchen", slug: "cooking", icon: "🍳", description: "Recipe converter, cooking time, calorie counter, gas cylinder & water TDS tools", color: "from-red-400 to-rose-500" },
  { name: "Wedding & Events", slug: "wedding", icon: "💒", description: "Wedding budget, guest list, auspicious dates, gift registry & event checklists", color: "from-pink-400 to-red-500" },
  { name: "Agriculture", slug: "agriculture", icon: "🌾", description: "Crop yield, fertilizer, irrigation, land measurement, farm profit & seed calculators", color: "from-lime-400 to-emerald-500" },
  { name: "Exam & Competitive", slug: "exam", icon: "📝", description: "NEET, JEE, GATE, CAT score predictors, board percentage & scholarship tools", color: "from-violet-400 to-indigo-500" },
  { name: "Vehicle & Transport", slug: "vehicle", icon: "🚗", description: "Mileage, road trip planner, insurance, tyre size, depreciation & toll calculators", color: "from-sky-400 to-cyan-500" },
  { name: "Astrology & Spiritual", slug: "astrology", icon: "🔮", description: "Kundli, Rashi, Nakshatra, Panchang, Numerology & Gemstone tools", color: "from-violet-400 to-purple-600" },
  { name: "Legal & Government", slug: "legal", icon: "⚖️", description: "Court fee calculator, legal notice, RTI application, affidavit & voter ID tools", color: "from-slate-500 to-gray-700" },
  { name: "AI Writing Tools", slug: "ai", icon: "🤖", description: "AI-powered paragraph rewriter, email writer, story generator, bio generator & more", color: "from-purple-400 to-indigo-600" },
];

export const tools: Tool[] = [
  // Finance Calculators
  { name: "EMI Calculator", slug: "emi-calculator", description: "Calculate Equated Monthly Installment for Home, Car & Personal loans", category: "finance", icon: "🏦", keywords: ["emi", "loan", "home loan", "car loan", "personal loan", "monthly installment"] },
  { name: "SIP Calculator", slug: "sip-calculator", description: "Calculate Systematic Investment Plan returns for Mutual Funds", category: "finance", icon: "📈", keywords: ["sip", "mutual fund", "investment", "returns", "wealth"] },
  { name: "GST Calculator", slug: "gst-calculator", description: "Calculate GST amount and total price with 5%, 12%, 18%, 28% rates", category: "finance", icon: "🧾", keywords: ["gst", "goods and services tax", "tax", "india tax"] },
  { name: "FD Calculator", slug: "fd-calculator", description: "Calculate Fixed Deposit maturity amount and interest earned", category: "finance", icon: "🏛️", keywords: ["fd", "fixed deposit", "bank", "interest", "maturity"] },
  { name: "RD Calculator", slug: "rd-calculator", description: "Calculate Recurring Deposit maturity amount and interest", category: "finance", icon: "💵", keywords: ["rd", "recurring deposit", "monthly saving", "interest"] },
  { name: "PPF Calculator", slug: "ppf-calculator", description: "Calculate Public Provident Fund maturity with yearly compounding", category: "finance", icon: "🏦", keywords: ["ppf", "public provident fund", "tax saving", "15 year"] },
  { name: "Compound Interest Calculator", slug: "compound-interest-calculator", description: "Calculate compound interest with different compounding frequencies", category: "finance", icon: "📊", keywords: ["compound interest", "ci", "interest", "investment"] },
  { name: "Simple Interest Calculator", slug: "simple-interest-calculator", description: "Calculate simple interest on principal amount", category: "finance", icon: "🧮", keywords: ["simple interest", "si", "principal", "rate"] },
  { name: "Income Tax Calculator", slug: "income-tax-calculator", description: "Calculate income tax under Old & New regime for India FY 2024-25", category: "finance", icon: "📋", keywords: ["income tax", "tax", "old regime", "new regime", "india"] },
  { name: "Gratuity Calculator", slug: "gratuity-calculator", description: "Calculate gratuity amount based on salary and years of service", category: "finance", icon: "🎁", keywords: ["gratuity", "retirement", "salary", "service"] },
  { name: "Lumpsum Calculator", slug: "lumpsum-calculator", description: "Calculate returns on one-time mutual fund investment", category: "finance", icon: "💎", keywords: ["lumpsum", "one time investment", "mutual fund", "returns"] },
  { name: "Salary Calculator", slug: "salary-calculator", description: "Calculate in-hand salary from CTC with PF, Tax & deductions", category: "finance", icon: "💼", keywords: ["salary", "ctc", "in hand", "take home", "pf", "deductions"] },
  { name: "Mutual Fund Calculator", slug: "mutual-fund-calculator", description: "Calculate SIP & Lumpsum mutual fund returns with visual breakdown", category: "finance", icon: "📊", keywords: ["mutual fund", "sip", "lumpsum", "investment", "returns", "nav"] },
  { name: "Car Loan Calculator", slug: "car-loan-calculator", description: "Calculate car loan EMI, total interest and monthly/yearly breakdown", category: "finance", icon: "🚗", keywords: ["car loan", "auto loan", "vehicle loan", "emi", "down payment"] },
  { name: "Home Loan Calculator", slug: "home-loan-calculator", description: "Calculate home loan EMI with year-wise principal vs interest breakdown", category: "finance", icon: "🏠", keywords: ["home loan", "housing loan", "mortgage", "emi", "property loan"] },
  { name: "Education Loan Calculator", slug: "education-loan-calculator", description: "Calculate education loan EMI with moratorium period and total cost", category: "finance", icon: "🎓", keywords: ["education loan", "student loan", "moratorium", "study loan", "college"] },
  { name: "Inflation Calculator", slug: "inflation-calculator", description: "Calculate future value needed and purchasing power loss due to inflation", category: "finance", icon: "📉", keywords: ["inflation", "purchasing power", "future value", "real value", "india inflation"] },
  { name: "CAGR Calculator", slug: "cagr-calculator", description: "Calculate Compound Annual Growth Rate, absolute return and growth multiple", category: "finance", icon: "📈", keywords: ["cagr", "compound annual growth", "absolute return", "growth", "investment"] },
  { name: "Sukanya Samriddhi Calculator", slug: "sukanya-samriddhi-calculator", description: "Calculate Sukanya Samriddhi Yojana maturity amount with year-wise growth", category: "finance", icon: "👧", keywords: ["sukanya samriddhi", "ssy", "girl child", "savings scheme", "80c"] },
  { name: "Post Office Savings Calculator", slug: "post-office-savings-calculator", description: "Calculate returns for NSC, KVP, SCSS, MIS & Time Deposit schemes", category: "finance", icon: "🏤", keywords: ["post office", "nsc", "kvp", "scss", "mis", "time deposit", "savings"] },

  // Math & Numbers
  { name: "Percentage Calculator", slug: "percentage-calculator", description: "Calculate percentages, percentage change, increase & decrease", category: "math", icon: "%", keywords: ["percentage", "percent", "increase", "decrease", "change"] },
  { name: "Age Calculator", slug: "age-calculator", description: "Calculate exact age in years, months, days from date of birth", category: "math", icon: "🎂", keywords: ["age", "birthday", "date of birth", "years old"] },
  { name: "BMI Calculator", slug: "bmi-calculator", description: "Calculate Body Mass Index and check health category", category: "math", icon: "⚖️", keywords: ["bmi", "body mass index", "weight", "height", "health"] },
  { name: "Discount Calculator", slug: "discount-calculator", description: "Calculate discount amount and final price after discount", category: "math", icon: "🏷️", keywords: ["discount", "sale", "offer", "price", "savings"] },
  { name: "Margin Calculator", slug: "margin-calculator", description: "Calculate profit margin, markup and selling price", category: "math", icon: "📐", keywords: ["margin", "profit", "markup", "cost", "selling price"] },
  { name: "Average Calculator", slug: "average-calculator", description: "Calculate mean, median, mode and range of numbers", category: "math", icon: "📊", keywords: ["average", "mean", "median", "mode", "statistics"] },
  { name: "Number to Words", slug: "number-to-words", description: "Convert numbers to words in Indian numbering system (Lakhs, Crores)", category: "math", icon: "🔤", keywords: ["number to words", "indian", "lakhs", "crores", "cheque"] },
  { name: "Random Number Generator", slug: "random-number-generator", description: "Generate random numbers within a specified range", category: "math", icon: "🎲", keywords: ["random", "number", "generator", "dice", "lottery"] },

  // Text Tools
  { name: "Word Counter", slug: "word-counter", description: "Count words, characters, sentences and paragraphs in text", category: "text", icon: "📊", keywords: ["word count", "character count", "sentence", "paragraph"] },
  { name: "Case Converter", slug: "case-converter", description: "Convert text to UPPERCASE, lowercase, Title Case, Sentence case", category: "text", icon: "Aa", keywords: ["uppercase", "lowercase", "title case", "sentence case", "capitalize"] },
  { name: "Lorem Ipsum Generator", slug: "lorem-ipsum-generator", description: "Generate placeholder Lorem Ipsum text for design and development", category: "text", icon: "📄", keywords: ["lorem ipsum", "placeholder", "dummy text", "filler"] },
  { name: "Text Repeater", slug: "text-repeater", description: "Repeat any text multiple times with custom separator", category: "text", icon: "🔁", keywords: ["repeat text", "duplicate", "multiply", "copy"] },
  { name: "Remove Duplicate Lines", slug: "remove-duplicate-lines", description: "Remove duplicate lines from text and keep unique lines only", category: "text", icon: "🧹", keywords: ["remove duplicates", "unique lines", "clean text"] },
  { name: "Text to Slug", slug: "text-to-slug", description: "Convert text to URL-friendly slug format", category: "text", icon: "🔗", keywords: ["slug", "url", "seo friendly", "permalink"] },
  { name: "Fancy Text Generator", slug: "fancy-text-generator", description: "Convert text to fancy Unicode fonts for social media", category: "text", icon: "✨", keywords: ["fancy text", "stylish text", "unicode", "instagram", "social media"] },
  { name: "Text Reverser", slug: "text-reverser", description: "Reverse any text string character by character", category: "text", icon: "↩️", keywords: ["reverse text", "backwards", "mirror", "flip"] },
  { name: "Plagiarism Checker", slug: "plagiarism-checker", description: "Compare two texts and detect matching or similar sentences with similarity percentage", category: "text", icon: "🔎", keywords: ["plagiarism", "duplicate", "similarity", "compare", "copy check"] },
  { name: "Readability Checker", slug: "readability-checker", description: "Calculate Flesch Reading Ease, Flesch-Kincaid Grade Level and readability stats", category: "text", icon: "📖", keywords: ["readability", "flesch", "grade level", "reading ease", "complexity"] },
  { name: "Text to Speech", slug: "text-to-speech", description: "Convert text to speech using browser Web Speech API with voice and speed controls", category: "text", icon: "🔊", keywords: ["text to speech", "tts", "voice", "speak", "audio", "read aloud"] },
  { name: "Speech to Text", slug: "speech-to-text", description: "Convert speech to text using browser voice recognition with live transcription", category: "text", icon: "🎤", keywords: ["speech to text", "stt", "voice recognition", "dictation", "transcription"] },
  { name: "Paragraph Rewriter", slug: "paragraph-rewriter", description: "Rewrite paragraphs in formal, casual and shorter styles using synonym substitution", category: "text", icon: "✏️", keywords: ["rewrite", "paraphrase", "synonym", "formal", "casual", "rephrase"] },
  { name: "Grammar Checker", slug: "grammar-checker", description: "Check text for common grammar issues like double spaces, capitalization and confused words", category: "text", icon: "📝", keywords: ["grammar", "spelling", "check", "proofread", "writing", "errors"] },
  { name: "Sentence Counter", slug: "sentence-counter", description: "Count sentences, words, characters, paragraphs with reading and speaking time estimates", category: "text", icon: "🔢", keywords: ["sentence count", "word count", "paragraph", "reading time", "speaking time"] },
  { name: "Text Encryption", slug: "text-encryption", description: "Encrypt and decrypt text using Caesar Cipher, ROT13, Base64, Reverse and Atbash methods", category: "text", icon: "🔐", keywords: ["encrypt", "decrypt", "cipher", "caesar", "rot13", "base64", "atbash"] },

  // Converter Tools
  { name: "Length Converter", slug: "length-converter", description: "Convert between meters, feet, inches, cm, km, miles & more", category: "converters", icon: "📏", keywords: ["length", "meter", "feet", "inch", "cm", "km", "miles"] },
  { name: "Weight Converter", slug: "weight-converter", description: "Convert between kg, pounds, ounces, grams & more", category: "converters", icon: "⚖️", keywords: ["weight", "kg", "pounds", "ounces", "grams", "mass"] },
  { name: "Temperature Converter", slug: "temperature-converter", description: "Convert between Celsius, Fahrenheit and Kelvin", category: "converters", icon: "🌡️", keywords: ["temperature", "celsius", "fahrenheit", "kelvin"] },
  { name: "Speed Converter", slug: "speed-converter", description: "Convert between km/h, mph, m/s, knots & more", category: "converters", icon: "🚀", keywords: ["speed", "kmph", "mph", "velocity"] },
  { name: "Data Storage Converter", slug: "data-storage-converter", description: "Convert between bytes, KB, MB, GB, TB and PB", category: "converters", icon: "💾", keywords: ["data", "bytes", "kb", "mb", "gb", "tb", "storage"] },
  { name: "Area Converter", slug: "area-converter", description: "Convert between sq meters, sq feet, acres, hectares & more", category: "converters", icon: "📐", keywords: ["area", "square meter", "square feet", "acres", "hectares", "bigha"] },
  { name: "Volume Converter", slug: "volume-converter", description: "Convert between liters, gallons, ml, cubic meters & more", category: "converters", icon: "🫗", keywords: ["volume", "liters", "gallons", "ml", "cubic"] },
  { name: "Number System Converter", slug: "number-system-converter", description: "Convert between Binary, Octal, Decimal and Hexadecimal", category: "converters", icon: "🔢", keywords: ["binary", "octal", "decimal", "hexadecimal", "base"] },

  // Developer Tools
  { name: "JSON Formatter", slug: "json-formatter", description: "Format, validate and beautify JSON data with syntax highlighting", category: "developer", icon: "{}", keywords: ["json", "format", "beautify", "validate", "minify"] },
  { name: "Base64 Encoder/Decoder", slug: "base64-encoder-decoder", description: "Encode text to Base64 or decode Base64 to text", category: "developer", icon: "🔐", keywords: ["base64", "encode", "decode", "encryption"] },
  { name: "URL Encoder/Decoder", slug: "url-encoder-decoder", description: "Encode or decode URLs and query parameters", category: "developer", icon: "🔗", keywords: ["url", "encode", "decode", "uri", "query string"] },
  { name: "HTML Encoder/Decoder", slug: "html-encoder-decoder", description: "Encode special characters to HTML entities or decode them", category: "developer", icon: "</>", keywords: ["html", "encode", "decode", "entities", "special characters"] },
  { name: "Color Picker & Converter", slug: "color-picker", description: "Pick colors and convert between HEX, RGB, HSL formats", category: "developer", icon: "🎨", keywords: ["color", "hex", "rgb", "hsl", "picker", "converter"] },
  { name: "Hash Generator", slug: "hash-generator", description: "Generate MD5, SHA-1, SHA-256 hash from text", category: "developer", icon: "#️⃣", keywords: ["hash", "md5", "sha", "sha256", "checksum"] },
  { name: "Regex Tester", slug: "regex-tester", description: "Test and debug regular expressions with real-time matching", category: "developer", icon: ".*", keywords: ["regex", "regular expression", "pattern", "match", "test"] },
  { name: "CSS Minifier", slug: "css-minifier", description: "Minify CSS code to reduce file size", category: "developer", icon: "🎨", keywords: ["css", "minify", "compress", "optimize", "stylesheet"] },
  { name: "JavaScript Minifier", slug: "javascript-minifier", description: "Minify JavaScript code to reduce file size", category: "developer", icon: "⚡", keywords: ["javascript", "js", "minify", "compress", "optimize"] },
  { name: "SQL Formatter", slug: "sql-formatter", description: "Format and beautify SQL queries for better readability", category: "developer", icon: "🗄️", keywords: ["sql", "format", "beautify", "query", "database"] },
  { name: "Cron Expression Generator", slug: "cron-expression-generator", description: "Build cron expressions visually with presets and next run times", category: "developer", icon: "🕐", keywords: ["cron", "crontab", "schedule", "job", "timer", "expression"] },
  { name: "JWT Decoder", slug: "jwt-decoder", description: "Decode JWT tokens and view header, payload, expiry with color-coded sections", category: "developer", icon: "🔓", keywords: ["jwt", "json web token", "decode", "token", "auth", "bearer"] },
  { name: "JSON Validator", slug: "json-validator", description: "Validate, beautify and analyze JSON with error line numbers and stats", category: "developer", icon: "✅", keywords: ["json", "validate", "lint", "check", "format", "beautify"] },
  { name: "XML to JSON Converter", slug: "xml-to-json", description: "Convert XML to JSON using DOMParser with attribute support", category: "developer", icon: "🔄", keywords: ["xml", "json", "convert", "parse", "transform"] },
  { name: "YAML to JSON Converter", slug: "yaml-to-json", description: "Convert YAML text to JSON format with basic YAML parsing", category: "developer", icon: "📄", keywords: ["yaml", "yml", "json", "convert", "config", "parse"] },
  { name: "HTML to Markdown", slug: "html-to-markdown", description: "Convert HTML to Markdown handling headings, lists, tables, links & code", category: "developer", icon: "📝", keywords: ["html", "markdown", "convert", "md", "markup"] },
  { name: "Markdown to HTML", slug: "markdown-to-html", description: "Convert Markdown to HTML with live preview and raw code output", category: "developer", icon: "📋", keywords: ["markdown", "html", "convert", "preview", "render"] },
  { name: "Code Beautifier", slug: "code-beautifier", description: "Format and beautify HTML, CSS, JavaScript, JSON and SQL code", category: "developer", icon: "💎", keywords: ["beautify", "format", "indent", "prettify", "code", "html", "css", "js", "sql"] },

  // Image Tools
  { name: "Image Compressor", slug: "image-compressor", description: "Compress images to reduce file size without losing quality", category: "image", icon: "📦", keywords: ["image", "compress", "reduce", "size", "optimize"] },
  { name: "Image Resizer", slug: "image-resizer", description: "Resize images to exact dimensions or percentage", category: "image", icon: "↔️", keywords: ["image", "resize", "dimensions", "scale", "width", "height"] },
  { name: "Image to PNG Converter", slug: "image-to-png", description: "Convert JPG, WebP, BMP images to PNG format", category: "image", icon: "🖼️", keywords: ["image", "png", "convert", "jpg to png"] },
  { name: "Image to JPG Converter", slug: "image-to-jpg", description: "Convert PNG, WebP, BMP images to JPG format", category: "image", icon: "📸", keywords: ["image", "jpg", "jpeg", "convert", "png to jpg"] },
  { name: "Image Cropper", slug: "image-cropper", description: "Crop images to custom dimensions with preview", category: "image", icon: "✂️", keywords: ["image", "crop", "cut", "trim", "resize"] },
  { name: "QR Code Generator", slug: "qr-code-generator", description: "Generate QR codes for URLs, text, WiFi, phone numbers", category: "image", icon: "📱", keywords: ["qr code", "qr", "barcode", "scan", "generate"] },
  { name: "Screenshot to Code", slug: "screenshot-to-code", description: "Extract color palette and dimensions from screenshots", category: "image", icon: "🖥️", keywords: ["screenshot", "color palette", "extract", "dimensions"] },
  { name: "Favicon Generator", slug: "favicon-generator", description: "Generate favicons in multiple sizes from any image", category: "image", icon: "⭐", keywords: ["favicon", "icon", "website icon", "generate"] },
  { name: "Meme Generator", slug: "meme-generator", description: "Create memes with custom text on uploaded images or preset templates", category: "image", icon: "😂", keywords: ["meme", "meme generator", "funny", "image text", "top text", "bottom text"] },
  { name: "Image Watermark", slug: "image-watermark", description: "Add custom text watermark to images with position, opacity and font controls", category: "image", icon: "💧", keywords: ["watermark", "image", "protect", "copyright", "overlay", "text"] },
  { name: "Background Remover", slug: "background-remover", description: "Remove solid color backgrounds from images using color threshold detection", category: "image", icon: "🪄", keywords: ["background remover", "transparent", "remove bg", "cutout", "alpha"] },
  { name: "Image Filters", slug: "image-filters", description: "Apply grayscale, sepia, blur, brightness, contrast and more filters to images", category: "image", icon: "🎞️", keywords: ["image filter", "grayscale", "sepia", "blur", "brightness", "contrast", "saturate"] },
  { name: "Collage Maker", slug: "collage-maker", description: "Create photo collages with multiple layouts, gap control and background color", category: "image", icon: "🖼️", keywords: ["collage", "photo collage", "grid", "layout", "combine images"] },
  { name: "Image Rotate & Flip", slug: "image-rotate-flip", description: "Rotate images 90/180 degrees and flip horizontally or vertically", category: "image", icon: "🔄", keywords: ["rotate", "flip", "mirror", "image", "horizontal", "vertical", "90 degrees"] },
  { name: "Passport Photo Maker", slug: "passport-photo-maker", description: "Create passport, visa, Aadhaar and PAN card photos with crop guides at 300 DPI", category: "image", icon: "🪪", keywords: ["passport photo", "visa photo", "aadhaar", "pan card", "id photo", "2x2"] },
  { name: "HEIC to JPG Converter", slug: "heic-to-jpg", description: "Convert HEIC and other image formats to JPG with quality control", category: "image", icon: "🔄", keywords: ["heic", "heif", "jpg", "jpeg", "convert", "iphone", "apple"] },
  { name: "Photo to Sketch", slug: "photo-to-sketch", description: "Convert photos to pencil sketch effect with adjustable intensity", category: "image", icon: "✏️", keywords: ["sketch", "pencil", "drawing", "art", "effect", "photo"] },
  { name: "Blur Background", slug: "blur-background", description: "Blur image background while keeping the subject sharp with rectangle selection", category: "image", icon: "🔲", keywords: ["blur", "background", "bokeh", "portrait", "depth", "focus"] },
  { name: "Photo Enhancer", slug: "photo-enhancer", description: "Auto-enhance photos with brightness, contrast, saturation and sharpness controls", category: "image", icon: "✨", keywords: ["enhance", "photo", "brightness", "contrast", "saturation", "sharpness", "auto"] },
  { name: "Image to WebP Converter", slug: "image-to-webp", description: "Convert JPG and PNG images to WebP format for smaller file sizes", category: "image", icon: "🌐", keywords: ["webp", "convert", "jpg to webp", "png to webp", "compress"] },
  { name: "WebP to JPG Converter", slug: "webp-to-jpg", description: "Convert WebP images to JPG format with quality control", category: "image", icon: "📸", keywords: ["webp", "jpg", "jpeg", "convert", "webp to jpg"] },
  { name: "WebP to PNG Converter", slug: "webp-to-png", description: "Convert WebP images to lossless PNG format", category: "image", icon: "🖼️", keywords: ["webp", "png", "convert", "webp to png", "lossless"] },
  { name: "Instagram Grid Maker", slug: "instagram-grid-maker", description: "Split images into grid pieces for seamless Instagram profile layouts", category: "image", icon: "📐", keywords: ["instagram", "grid", "split", "profile", "3x3", "mosaic", "carousel"] },
  { name: "Certificate Generator", slug: "certificate-generator", description: "Create beautiful certificates with customizable templates, borders and fonts", category: "image", icon: "📜", keywords: ["certificate", "award", "achievement", "diploma", "generate", "template"] },
  { name: "Thumbnail Maker", slug: "thumbnail-maker", description: "Create eye-catching thumbnails for YouTube, blogs and social media", category: "image", icon: "🎬", keywords: ["thumbnail", "youtube", "blog", "cover", "banner", "title", "overlay"] },
  { name: "Avatar Profile Pic Maker", slug: "avatar-profile-pic-maker", description: "Create circle or square profile pictures with borders and custom sizes", category: "image", icon: "👤", keywords: ["avatar", "profile picture", "dp", "circle crop", "profile pic", "pfp"] },
  { name: "Photo Frame Maker", slug: "photo-frame-maker", description: "Add beautiful frames to photos including Polaroid, wood, Diwali and Christmas styles", category: "image", icon: "🖼️", keywords: ["frame", "photo frame", "polaroid", "border", "diwali", "christmas", "decoration"] },
  { name: "Color Palette Extractor", slug: "color-palette-extractor", description: "Extract dominant colors from any image with HEX and RGB values", category: "image", icon: "🎨", keywords: ["color palette", "extract colors", "dominant color", "hex", "rgb", "image colors"] },
  { name: "Image to ASCII Art", slug: "image-to-ascii-art", description: "Convert images to ASCII text art with adjustable width and dark/light modes", category: "image", icon: "🔤", keywords: ["ascii", "ascii art", "text art", "image to text", "convert", "monospace"] },
  { name: "Photo Color Changer", slug: "photo-color-changer", description: "Replace any color in your photo with another color using eyedropper and tolerance control", category: "image", icon: "🎨", keywords: ["color changer", "replace color", "photo color", "swap color", "eyedropper", "hue"] },
  { name: "Red Eye Remover", slug: "red-eye-remover", description: "Remove red eye from photos by clicking on affected areas", category: "image", icon: "👁️", keywords: ["red eye", "remove red eye", "photo fix", "eye correction", "portrait"] },
  { name: "Old Photo Restorer", slug: "old-photo-restorer", description: "Restore and enhance old photos with contrast, brightness, sharpening and de-yellowing", category: "image", icon: "📷", keywords: ["restore photo", "old photo", "enhance", "vintage", "repair", "sharpen", "de-yellow"] },
  { name: "Noise Reducer", slug: "noise-reducer", description: "Reduce noise and grain from photos using median filter with adjustable intensity", category: "image", icon: "🔇", keywords: ["noise reduction", "denoise", "grain removal", "smooth", "clean", "filter"] },
  { name: "SVG to PNG Converter", slug: "svg-to-png", description: "Convert SVG code or files to PNG images at custom dimensions", category: "image", icon: "🔀", keywords: ["svg", "png", "convert", "vector", "raster", "export"] },
  { name: "Bulk Image Resizer", slug: "bulk-image-resizer", description: "Resize multiple images at once by percentage or exact dimensions", category: "image", icon: "📐", keywords: ["bulk resize", "batch resize", "multiple images", "scale", "dimensions"] },
  { name: "Image DPI Changer", slug: "image-dpi-changer", description: "Change image DPI for print with physical size calculations in inches and cm", category: "image", icon: "🖨️", keywords: ["dpi", "ppi", "print", "resolution", "300dpi", "72dpi", "inches", "cm"] },
  { name: "Screenshot Beautifier", slug: "screenshot-beautifier", description: "Add device mockup frames, backgrounds and shadows to screenshots", category: "image", icon: "✨", keywords: ["screenshot", "mockup", "beautify", "browser frame", "macbook", "iphone", "device"] },
  { name: "Image Text Extractor (OCR)", slug: "image-text-extractor-ocr", description: "Detect text regions in images with enhancement tools and links to free OCR services", category: "image", icon: "🔍", keywords: ["ocr", "text extraction", "image text", "detect text", "read text", "scan"] },
  { name: "Image Comparison Slider", slug: "image-comparison-slider", description: "Compare two images side by side with a draggable slider, overlay and fullscreen modes", category: "image", icon: "🔀", keywords: ["compare", "before after", "slider", "image diff", "overlay", "side by side"] },
  { name: "Photo Calendar Maker", slug: "photo-calendar-maker", description: "Create printable photo calendars with Indian holidays in Classic, Modern and Colorful styles", category: "image", icon: "📅", keywords: ["calendar", "photo calendar", "monthly", "indian holidays", "printable", "wall calendar"] },
  { name: "ID Card Generator", slug: "id-card-generator", description: "Generate professional ID cards with photo for Corporate, School and Hospital templates at 300 DPI", category: "image", icon: "🪪", keywords: ["id card", "identity card", "employee id", "school id", "hospital id", "badge"] },
  { name: "Business Card Maker", slug: "business-card-maker", description: "Design business cards with Minimal, Dark, Corporate and Gradient styles at 300 DPI print quality", category: "image", icon: "💼", keywords: ["business card", "visiting card", "card maker", "professional", "print", "contact card"] },
  { name: "Pixel Art Maker", slug: "pixel-art-maker", description: "Convert photos to pixel art with adjustable block size and color palette reduction", category: "image", icon: "👾", keywords: ["pixel art", "pixelate", "8-bit", "retro", "mosaic", "block art", "low poly"] },
  { name: "Image Border Adder", slug: "image-border-adder", description: "Add borders to images with Solid, Gradient, Double Line, Rounded and Shadow styles", category: "image", icon: "🖼️", keywords: ["border", "frame", "image border", "solid border", "gradient border", "rounded", "shadow"] },

  // SEO Tools
  { name: "Meta Tag Generator", slug: "meta-tag-generator", description: "Generate SEO-friendly meta tags for your website", category: "seo", icon: "🏷️", keywords: ["meta tags", "seo", "title", "description", "og tags"] },
  { name: "Open Graph Generator", slug: "open-graph-generator", description: "Generate Open Graph meta tags for social media sharing", category: "seo", icon: "📱", keywords: ["open graph", "og", "facebook", "twitter", "social media"] },
  { name: "Robots.txt Generator", slug: "robots-txt-generator", description: "Generate robots.txt file for search engine crawlers", category: "seo", icon: "🤖", keywords: ["robots.txt", "seo", "crawler", "search engine", "sitemap"] },
  { name: "XML Sitemap Generator", slug: "sitemap-generator", description: "Generate XML sitemap for your website pages", category: "seo", icon: "🗺️", keywords: ["sitemap", "xml", "seo", "pages", "crawl"] },
  { name: "UTM Link Builder", slug: "utm-link-builder", description: "Create UTM tagged URLs for campaign tracking", category: "seo", icon: "🔗", keywords: ["utm", "campaign", "tracking", "google analytics", "link builder"] },
  { name: "Keyword Density Checker", slug: "keyword-density-checker", description: "Analyze keyword density and frequency in your content", category: "seo", icon: "📊", keywords: ["keyword density", "seo", "content", "frequency", "analysis"] },
  { name: "Schema Markup Generator", slug: "schema-markup-generator", description: "Generate JSON-LD schema markup for rich search results", category: "seo", icon: "📋", keywords: ["schema", "json-ld", "structured data", "rich snippets", "seo"] },
  { name: "Twitter Card Generator", slug: "twitter-card-generator", description: "Generate Twitter Card meta tags for better social sharing", category: "seo", icon: "🐦", keywords: ["twitter card", "social media", "meta tags", "sharing"] },

  // Date & Time
  { name: "Date Difference Calculator", slug: "date-difference-calculator", description: "Calculate difference between two dates in days, months, years", category: "datetime", icon: "📅", keywords: ["date difference", "days between", "duration", "gap"] },
  { name: "Countdown Timer", slug: "countdown-timer", description: "Create countdown timer to any future date or event", category: "datetime", icon: "⏳", keywords: ["countdown", "timer", "event", "days left", "remaining"] },
  { name: "Timezone Converter", slug: "timezone-converter", description: "Convert time between different timezones worldwide", category: "datetime", icon: "🌍", keywords: ["timezone", "time zone", "convert", "ist", "utc", "pst"] },
  { name: "Unix Timestamp Converter", slug: "unix-timestamp-converter", description: "Convert between Unix timestamp and human-readable date", category: "datetime", icon: "⏰", keywords: ["unix", "timestamp", "epoch", "convert", "date"] },
  { name: "Date Add/Subtract", slug: "date-add-subtract", description: "Add or subtract days, months, years from a date", category: "datetime", icon: "➕", keywords: ["date add", "date subtract", "add days", "future date"] },
  { name: "Working Days Calculator", slug: "working-days-calculator", description: "Calculate working days between two dates excluding weekends", category: "datetime", icon: "💼", keywords: ["working days", "business days", "weekdays", "exclude weekends"] },
  { name: "Stopwatch", slug: "stopwatch", description: "Online stopwatch with lap timing and millisecond precision", category: "datetime", icon: "⏱️", keywords: ["stopwatch", "timer", "lap", "time", "clock"] },
  { name: "World Clock", slug: "world-clock", description: "See current time in major cities across the world", category: "datetime", icon: "🕐", keywords: ["world clock", "time", "cities", "global", "current time"] },

  // Security & Privacy
  { name: "Password Generator", slug: "password-generator", description: "Generate strong, secure random passwords with custom length and characters", category: "security", icon: "🔐", keywords: ["password", "generator", "strong", "secure", "random"] },
  { name: "Privacy Policy Generator", slug: "privacy-policy-generator", description: "Generate a free privacy policy for your website or app", category: "security", icon: "📜", keywords: ["privacy policy", "gdpr", "website", "legal", "generator"] },
  { name: "Terms & Conditions Generator", slug: "terms-conditions-generator", description: "Generate terms and conditions for your website or app", category: "security", icon: "📋", keywords: ["terms", "conditions", "legal", "website", "agreement"] },

  // Health & Fitness
  { name: "BMR Calculator", slug: "bmr-calculator", description: "Calculate Basal Metabolic Rate and daily calorie needs", category: "health", icon: "🔥", keywords: ["bmr", "basal metabolic rate", "calories", "metabolism", "tdee"] },
  { name: "Calorie Calculator", slug: "calorie-calculator", description: "Calculate daily calorie intake for weight loss, gain or maintenance", category: "health", icon: "🍎", keywords: ["calorie", "diet", "weight loss", "nutrition", "calories per day"] },
  { name: "Pregnancy Calculator", slug: "pregnancy-calculator", description: "Calculate due date, conception date and pregnancy week from LMP", category: "health", icon: "🤰", keywords: ["pregnancy", "due date", "conception", "trimester", "lmp", "weeks pregnant"] },
  { name: "Water Intake Calculator", slug: "water-intake-calculator", description: "Calculate how much water you should drink daily based on weight and activity", category: "health", icon: "💧", keywords: ["water intake", "hydration", "daily water", "drink water"] },
  { name: "Body Fat Calculator", slug: "body-fat-calculator", description: "Estimate body fat percentage using US Navy method", category: "health", icon: "📏", keywords: ["body fat", "percentage", "navy method", "fitness"] },

  // Tax & Salary (India specific)
  { name: "HRA Exemption Calculator", slug: "hra-calculator", description: "Calculate HRA exemption for income tax under Section 10(13A)", category: "tax", icon: "🏠", keywords: ["hra", "house rent allowance", "exemption", "tax saving", "section 10"] },
  { name: "EPF Calculator", slug: "epf-calculator", description: "Calculate Employee Provident Fund maturity amount and interest", category: "tax", icon: "🏦", keywords: ["epf", "provident fund", "pf", "retirement", "employee"] },
  { name: "NPS Calculator", slug: "nps-calculator", description: "Calculate National Pension System returns and pension amount", category: "tax", icon: "👴", keywords: ["nps", "national pension", "retirement", "pension", "annuity"] },
  { name: "TDS Calculator", slug: "tds-calculator", description: "Calculate Tax Deducted at Source for salary, rent, interest & more", category: "tax", icon: "💳", keywords: ["tds", "tax deducted", "source", "salary tds", "rent tds"] },
  { name: "Stamp Duty Calculator", slug: "stamp-duty-calculator", description: "Calculate stamp duty and registration charges state-wise in India", category: "tax", icon: "🏡", keywords: ["stamp duty", "registration", "property", "state wise", "india"] },
  { name: "Rent Receipt Generator", slug: "rent-receipt-generator", description: "Generate rent receipts for HRA tax exemption claims", category: "tax", icon: "🧾", keywords: ["rent receipt", "hra claim", "landlord", "tax exemption"] },
  { name: "Salary Hike Calculator", slug: "salary-hike-calculator", description: "Calculate new salary after percentage hike during appraisal", category: "tax", icon: "📈", keywords: ["salary hike", "appraisal", "increment", "percentage increase"] },
  { name: "Electricity Bill Calculator", slug: "electricity-bill-calculator", description: "Calculate monthly electricity bill based on units consumed and state tariff", category: "tax", icon: "⚡", keywords: ["electricity bill", "bijli bill", "units", "tariff", "state wise"] },
  { name: "Gold Price Calculator", slug: "gold-price-calculator", description: "Calculate gold value based on weight, purity (karat) and current price", category: "tax", icon: "🥇", keywords: ["gold", "price", "karat", "24k", "22k", "value", "calculator"] },

  // Fun & Utility
  { name: "Typing Speed Test", slug: "typing-speed-test", description: "Test your typing speed and accuracy in WPM with real-time results", category: "fun", icon: "⌨️", keywords: ["typing", "speed test", "wpm", "words per minute", "typing test"] },
  { name: "Love Calculator", slug: "love-calculator", description: "Fun love compatibility calculator - check your love percentage", category: "fun", icon: "❤️", keywords: ["love calculator", "compatibility", "love percentage", "crush"] },
  { name: "Flip a Coin", slug: "flip-a-coin", description: "Virtual coin flip - Heads or Tails with animation", category: "fun", icon: "🪙", keywords: ["flip coin", "heads tails", "coin toss", "random"] },
  { name: "Roll a Dice", slug: "roll-a-dice", description: "Virtual dice roller with 1 to 6 dice and animation", category: "fun", icon: "🎲", keywords: ["roll dice", "dice roller", "random", "board game"] },
  { name: "Pomodoro Timer", slug: "pomodoro-timer", description: "Pomodoro technique timer for focused work sessions (25/5 min)", category: "fun", icon: "🍅", keywords: ["pomodoro", "timer", "focus", "productivity", "25 minutes"] },
  { name: "Scientific Calculator", slug: "scientific-calculator", description: "Advanced scientific calculator with sin, cos, tan, log, power functions", category: "fun", icon: "🔬", keywords: ["scientific calculator", "sin", "cos", "tan", "log", "math"] },
  { name: "Fuel Cost Calculator", slug: "fuel-cost-calculator", description: "Calculate fuel cost for a trip based on distance, mileage and fuel price", category: "fun", icon: "⛽", keywords: ["fuel cost", "petrol", "diesel", "trip cost", "mileage"] },
  { name: "Tip Calculator", slug: "tip-calculator", description: "Calculate tip amount and split bill among friends", category: "fun", icon: "💁", keywords: ["tip", "calculator", "bill split", "restaurant", "gratuity"] },
  { name: "Screen Resolution Checker", slug: "screen-resolution-checker", description: "Check your current screen resolution, DPI and device pixel ratio", category: "fun", icon: "🖥️", keywords: ["screen resolution", "display", "dpi", "pixel ratio", "monitor"] },
  { name: "IP Address Lookup", slug: "ip-address-lookup", description: "Find your public IP address and basic location information", category: "fun", icon: "🌐", keywords: ["ip address", "my ip", "public ip", "location", "lookup"] },

  // CSS & Design
  { name: "CSS Gradient Generator", slug: "css-gradient-generator", description: "Create beautiful CSS linear and radial gradients with live preview", category: "css", icon: "🌈", keywords: ["css gradient", "linear gradient", "radial", "background", "generator"] },
  { name: "Box Shadow Generator", slug: "box-shadow-generator", description: "Generate CSS box-shadow with visual editor and live preview", category: "css", icon: "🔲", keywords: ["box shadow", "css", "shadow", "generator", "visual"] },
  { name: "Border Radius Generator", slug: "border-radius-generator", description: "Generate CSS border-radius with visual editor for all corners", category: "css", icon: "⬜", keywords: ["border radius", "css", "rounded corners", "generator"] },
  { name: "Color Palette Generator", slug: "color-palette-generator", description: "Generate beautiful color palettes and color schemes for design", category: "css", icon: "🎨", keywords: ["color palette", "color scheme", "design", "colors", "generator"] },
  { name: "Glassmorphism Generator", slug: "glassmorphism-generator", description: "Generate CSS glassmorphism effect with blur, transparency and border", category: "css", icon: "🪟", keywords: ["glassmorphism", "glass effect", "css", "blur", "transparency"] },
  { name: "Text Shadow Generator", slug: "text-shadow-generator", description: "Generate CSS text-shadow with multiple layers and live preview", category: "css", icon: "✍️", keywords: ["text shadow", "css", "shadow", "generator", "typography"] },

  // Data Tools
  { name: "JSON to CSV Converter", slug: "json-to-csv", description: "Convert JSON data to CSV format for spreadsheets", category: "data", icon: "📊", keywords: ["json", "csv", "convert", "spreadsheet", "data"] },
  { name: "CSV to JSON Converter", slug: "csv-to-json", description: "Convert CSV data to JSON format for APIs", category: "data", icon: "📋", keywords: ["csv", "json", "convert", "api", "data"] },
  { name: "Text Diff Checker", slug: "text-diff-checker", description: "Compare two texts and find differences between them", category: "data", icon: "📝", keywords: ["diff", "compare", "text", "difference", "changes"] },
  { name: "Markdown Preview", slug: "markdown-preview", description: "Write and preview Markdown with live rendering", category: "data", icon: "📖", keywords: ["markdown", "preview", "editor", "md", "render"] },
  { name: "Image to Base64", slug: "image-to-base64", description: "Convert images to Base64 encoded string for embedding in code", category: "data", icon: "🖼️", keywords: ["image", "base64", "convert", "encode", "embed"] },
  { name: "Aspect Ratio Calculator", slug: "aspect-ratio-calculator", description: "Calculate and convert aspect ratios for images and videos", category: "data", icon: "📐", keywords: ["aspect ratio", "16:9", "4:3", "image", "video", "resolution"] },

  // Social Media
  { name: "Instagram Bio Generator", slug: "instagram-bio-generator", description: "Generate creative Instagram bios with professional, casual & creative styles", category: "social", icon: "📸", keywords: ["instagram", "bio", "profile", "social media", "generator"] },
  { name: "Hashtag Generator", slug: "hashtag-generator", description: "Generate 30 relevant hashtags grouped by popularity for Instagram & Twitter", category: "social", icon: "#️⃣", keywords: ["hashtag", "instagram", "twitter", "social media", "trending"] },
  { name: "Social Media Image Resizer", slug: "social-media-image-resizer", description: "Resize images for Instagram, Facebook, YouTube, LinkedIn & Twitter", category: "social", icon: "🖼️", keywords: ["resize", "image", "instagram", "facebook", "youtube", "social media"] },
  { name: "Tweet Character Counter", slug: "tweet-character-counter", description: "Count characters for Twitter (280), Instagram (2200), LinkedIn (3000) & Facebook", category: "social", icon: "🐦", keywords: ["twitter", "character count", "tweet", "instagram", "linkedin", "limit"] },
  { name: "YouTube Timestamp Generator", slug: "youtube-timestamp-generator", description: "Create formatted timestamps for YouTube video descriptions", category: "social", icon: "⏱️", keywords: ["youtube", "timestamp", "video", "chapters", "description"] },
  { name: "YouTube Thumbnail Downloader", slug: "youtube-thumbnail-downloader", description: "Download YouTube video thumbnails in all sizes from any video URL", category: "social", icon: "🎬", keywords: ["youtube", "thumbnail", "download", "video", "image"] },

  // Education
  { name: "GPA Calculator", slug: "gpa-calculator", description: "Calculate SGPA/CGPA with 10-point and 4-point grading scales", category: "education", icon: "🎓", keywords: ["gpa", "sgpa", "cgpa", "grade", "credits", "university"] },
  { name: "CGPA to Percentage", slug: "cgpa-to-percentage", description: "Convert CGPA to percentage using CBSE, VTU & other formulas", category: "education", icon: "📊", keywords: ["cgpa", "percentage", "cbse", "convert", "grade"] },
  { name: "Percentage to CGPA", slug: "percentage-to-cgpa", description: "Convert percentage to CGPA using multiple university formulas", category: "education", icon: "🔄", keywords: ["percentage", "cgpa", "convert", "university", "grade"] },
  { name: "Grade Calculator", slug: "grade-calculator", description: "Calculate percentage, grade and pass/fail status for multiple subjects", category: "education", icon: "📝", keywords: ["grade", "marks", "percentage", "pass", "fail", "result"] },
  { name: "Study Time Planner", slug: "study-time-planner", description: "Generate a study schedule based on subjects and available hours per day", category: "education", icon: "📅", keywords: ["study", "planner", "timetable", "schedule", "exam", "preparation"] },

  // Business
  { name: "GST Invoice Generator", slug: "gst-invoice-generator", description: "Generate formatted GST invoice with CGST/SGST breakdown for Indian businesses", category: "business", icon: "🧾", keywords: ["gst", "invoice", "cgst", "sgst", "tax", "billing", "india"] },
  { name: "Business Name Generator", slug: "business-name-generator", description: "Generate 20 creative business name ideas based on industry and keywords", category: "business", icon: "💡", keywords: ["business name", "company", "startup", "brand", "generator"] },
  { name: "Profit & Loss Calculator", slug: "profit-loss-calculator", description: "Calculate gross profit, operating profit, net profit and margins", category: "business", icon: "📈", keywords: ["profit", "loss", "margin", "revenue", "p&l", "income statement"] },
  { name: "Break-Even Calculator", slug: "break-even-calculator", description: "Calculate break-even point in units and revenue with profit visualization", category: "business", icon: "⚖️", keywords: ["break even", "fixed cost", "variable cost", "profit", "units"] },
  { name: "ROI Calculator", slug: "roi-calculator", description: "Calculate Return on Investment, annualized return and total profit/loss", category: "business", icon: "💰", keywords: ["roi", "return", "investment", "profit", "annualized"] },
  { name: "Home Loan Affordability", slug: "home-loan-affordability", description: "Calculate maximum home loan amount based on income and EMI-to-income ratio", category: "business", icon: "🏠", keywords: ["home loan", "affordability", "emi", "income", "eligibility", "housing"] },
  { name: "Rent vs Buy Calculator", slug: "rent-vs-buy-calculator", description: "Compare total cost of buying vs renting a property over a period", category: "business", icon: "🏡", keywords: ["rent", "buy", "property", "real estate", "comparison", "emi"] },
  { name: "Carpet Area Calculator", slug: "carpet-area-calculator", description: "Calculate carpet area from super built-up area using loading factor for Indian real estate", category: "business", icon: "📐", keywords: ["carpet area", "built up", "super built up", "loading factor", "rera", "real estate"] },

  // PDF Tools
  { name: "PDF to Word", slug: "pdf-to-word", description: "Extract text from PDF files and download as editable text document", category: "pdf", icon: "📄", keywords: ["pdf", "word", "text", "extract", "convert", "document"] },
  { name: "Word to PDF", slug: "word-to-pdf", description: "Convert text content to PDF document with title and formatting", category: "pdf", icon: "📝", keywords: ["word", "pdf", "text", "convert", "document", "generate"] },
  { name: "Merge PDF", slug: "merge-pdf", description: "Combine multiple PDF files into one merged document", category: "pdf", icon: "📎", keywords: ["merge", "pdf", "combine", "join", "multiple", "files"] },
  { name: "Split PDF", slug: "split-pdf", description: "Split PDF by page ranges and extract specific pages", category: "pdf", icon: "✂️", keywords: ["split", "pdf", "pages", "extract", "range", "separate"] },
  { name: "Compress PDF", slug: "compress-pdf", description: "Reduce PDF file size with low, medium and high compression levels", category: "pdf", icon: "📦", keywords: ["compress", "pdf", "reduce", "size", "optimize", "smaller"] },
  { name: "Image to PDF", slug: "image-to-pdf", description: "Convert multiple images to PDF with A4, Letter and Legal page sizes", category: "pdf", icon: "🖼️", keywords: ["image", "pdf", "convert", "jpg", "png", "photo"] },
  { name: "PDF to Image", slug: "pdf-to-image", description: "Get PDF file info and extract text content from PDF files", category: "pdf", icon: "🖼️", keywords: ["pdf", "image", "convert", "extract", "png", "jpg"] },
  { name: "PDF Page Remover", slug: "pdf-page-remover", description: "Remove specific pages from PDF and download remaining content", category: "pdf", icon: "🗑️", keywords: ["pdf", "remove", "delete", "pages", "page remover"] },

  // Converter Tools (additional)
  { name: "Currency Converter", slug: "currency-converter", description: "Convert between INR, USD, EUR, GBP, AED, SAR, JPY and more currencies", category: "converters", icon: "💱", keywords: ["currency", "converter", "inr", "usd", "eur", "exchange rate", "rupee", "dollar"] },
  { name: "Bytes Converter", slug: "bytes-converter", description: "Convert between Bytes, KB, MB, GB, TB and PB data units", category: "converters", icon: "💾", keywords: ["bytes", "kb", "mb", "gb", "tb", "data", "storage", "converter"] },
  { name: "HEX to RGB Converter", slug: "hex-to-rgb", description: "Convert between HEX, RGB and HSL color formats with preview", category: "converters", icon: "🎨", keywords: ["hex", "rgb", "hsl", "color", "converter", "css"] },
  { name: "Decimal to Binary", slug: "decimal-to-binary", description: "Convert between Decimal, Binary, Octal and Hexadecimal number systems", category: "converters", icon: "🔢", keywords: ["decimal", "binary", "octal", "hex", "number system", "base"] },
  { name: "Pixels to REM", slug: "pixels-to-rem", description: "Convert between Pixels and REM with conversion table for web development", category: "converters", icon: "📐", keywords: ["pixels", "rem", "px", "css", "font size", "web", "responsive"] },
  { name: "Feet to Meters", slug: "feet-to-meters", description: "Convert between Feet/Inches and Meters/CM for Indian real estate", category: "converters", icon: "📏", keywords: ["feet", "meters", "inches", "cm", "height", "length", "real estate"] },
  { name: "Liters to Gallons", slug: "liters-to-gallons", description: "Convert between Liters, US Gallons and Imperial Gallons", category: "converters", icon: "🫗", keywords: ["liters", "gallons", "imperial", "us", "volume", "liquid"] },
  { name: "Acres to Square Feet", slug: "acres-to-sqfeet", description: "Convert between Acres, Sq Feet, Hectares, Bigha, Guntha and Indian land units", category: "converters", icon: "🏗️", keywords: ["acres", "square feet", "hectares", "bigha", "guntha", "land", "area", "india"] },

  // Everyday Utility (8)
  { name: "Vehicle Number Info", slug: "vehicle-number-info", description: "Parse Indian vehicle registration number to find state, RTO district and vehicle type", category: "utility", icon: "🚗", keywords: ["vehicle", "registration", "number plate", "rto", "state code", "car number"] },
  { name: "IFSC Code Lookup", slug: "ifsc-code-lookup", description: "Look up bank name and branch details from IFSC code", category: "utility", icon: "🏦", keywords: ["ifsc", "bank", "branch", "neft", "rtgs", "imps", "code"] },
  { name: "PIN Code Lookup", slug: "pin-code-lookup", description: "Find postal zone and region from Indian 6-digit PIN code", category: "utility", icon: "📮", keywords: ["pin code", "postal", "zip", "india post", "zone", "region"] },
  { name: "PAN Card Validator", slug: "pan-card-validator", description: "Validate PAN card number format and identify holder type", category: "utility", icon: "💳", keywords: ["pan", "permanent account number", "tax", "validate", "income tax"] },
  { name: "Aadhaar Validator", slug: "aadhaar-validator", description: "Validate Aadhaar number format using Verhoeff checksum algorithm", category: "utility", icon: "🆔", keywords: ["aadhaar", "aadhar", "uid", "uidai", "validate", "verhoeff"] },
  { name: "GST Number Validator", slug: "gst-number-validator", description: "Validate GSTIN format and extract state, PAN and entity details", category: "utility", icon: "🧾", keywords: ["gst", "gstin", "validate", "tax", "goods services", "state code"] },
  { name: "Indian Railway PNR", slug: "indian-railway-pnr", description: "Understand PNR number format with railway zone codes and IRCTC links", category: "utility", icon: "🚂", keywords: ["pnr", "railway", "irctc", "train", "indian railway", "zone"] },
  { name: "Ration Card Info", slug: "ration-card-info", description: "Types of ration cards in India - AAY, PHH, NPHH eligibility and benefits", category: "utility", icon: "🪪", keywords: ["ration card", "aay", "phh", "bpl", "food", "nfsa", "pds"] },

  // Fun & Games (additional 8)
  { name: "Random Name Generator", slug: "random-name-generator", description: "Generate random Indian names by gender and origin - Hindu, Muslim, Sikh, Christian", category: "fun", icon: "🎲", keywords: ["random name", "indian name", "hindu name", "muslim name", "name generator"] },
  { name: "Baby Name Generator", slug: "baby-name-generator", description: "Generate baby names with meanings - filter by letter, gender and origin", category: "fun", icon: "👶", keywords: ["baby name", "name meaning", "hindu baby", "muslim baby", "name suggestion"] },
  { name: "Numerology Calculator", slug: "numerology-calculator", description: "Calculate Life Path, Expression and Soul Urge numbers from name and DOB", category: "fun", icon: "🔮", keywords: ["numerology", "life path", "expression number", "soul urge", "spiritual"] },
  { name: "Lucky Number Generator", slug: "lucky-number-generator", description: "Find your lucky numbers, colors, days and gemstone based on numerology", category: "fun", icon: "🍀", keywords: ["lucky number", "numerology", "lucky color", "lucky day", "gemstone"] },
  { name: "Would You Rather", slug: "would-you-rather", description: "Fun Would You Rather game with 50+ questions and percentage results", category: "fun", icon: "🤔", keywords: ["would you rather", "game", "fun", "choice", "party game"] },
  { name: "Truth or Dare", slug: "truth-or-dare", description: "Truth or Dare game with Mild, Medium and Spicy difficulty levels", category: "fun", icon: "🔥", keywords: ["truth or dare", "game", "party", "fun", "dare", "truth"] },
  { name: "Quote Generator", slug: "quote-generator", description: "Random motivational and inspirational quotes from famous personalities", category: "fun", icon: "💬", keywords: ["quote", "motivational", "inspirational", "famous", "gandhi", "kalam"] },
  { name: "Nickname Generator", slug: "nickname-generator", description: "Generate fun nicknames based on your name and personality vibe", category: "fun", icon: "😎", keywords: ["nickname", "funny name", "cool name", "username", "generator"] },

  // SEO & Marketing Tools (additional)
  { name: "SERP Preview", slug: "serp-preview", description: "Preview how your page looks in Google search results with real-time character counts", category: "seo", icon: "🔎", keywords: ["serp", "preview", "google", "search result", "title", "meta description"] },
  { name: "Headline Analyzer", slug: "headline-analyzer", description: "Analyze headlines for power words, emotional appeal and SEO score", category: "seo", icon: "📰", keywords: ["headline", "analyzer", "title", "score", "power words", "seo"] },
  { name: "Backlink Checker", slug: "backlink-checker", description: "Check backlinks with Google search operators and backlink tool guidance", category: "seo", icon: "🔗", keywords: ["backlink", "checker", "domain", "seo", "link building", "authority"] },
  { name: "Domain Age Checker", slug: "domain-age-checker", description: "Check domain age with WHOIS lookup links and age calculator", category: "seo", icon: "📅", keywords: ["domain age", "whois", "registration", "domain", "age checker"] },
  { name: "Page Speed Estimator", slug: "page-speed-estimator", description: "Estimate page speed score with optimization checklist and tips", category: "seo", icon: "⚡", keywords: ["page speed", "performance", "optimization", "loading", "lighthouse"] },
  { name: "Sitemap Validator", slug: "sitemap-validator", description: "Validate XML sitemap structure, URLs, lastmod and priority values", category: "seo", icon: "🗺️", keywords: ["sitemap", "xml", "validate", "urls", "seo", "crawl"] },

  // Health & Fitness (additional)
  { name: "Blood Alcohol Calculator", slug: "blood-alcohol-calculator", description: "Calculate BAC using Widmark formula with Indian legal limit (0.03%)", category: "health", icon: "🍷", keywords: ["blood alcohol", "bac", "widmark", "drink", "sober", "legal limit"] },
  { name: "Heart Rate Zone Calculator", slug: "heart-rate-zone-calculator", description: "Calculate 5 heart rate training zones based on age and resting HR", category: "health", icon: "💓", keywords: ["heart rate", "zone", "training", "cardio", "exercise", "karvonen"] },
  { name: "Macro Calculator", slug: "macro-calculator", description: "Calculate daily macros (protein, carbs, fat) for different diets and goals", category: "health", icon: "🥗", keywords: ["macro", "macronutrient", "protein", "carbs", "fat", "diet", "keto", "tdee"] },
  { name: "Ideal Weight Calculator", slug: "ideal-weight-calculator", description: "Calculate ideal body weight using Devine, Robinson, Miller & Hamwi formulas", category: "health", icon: "⚖️", keywords: ["ideal weight", "body weight", "devine", "robinson", "miller", "hamwi"] },
  { name: "Protein Intake Calculator", slug: "protein-intake-calculator", description: "Calculate daily protein needs based on weight, activity and fitness goal", category: "health", icon: "🥩", keywords: ["protein", "intake", "daily", "muscle", "fitness", "grams"] },
  { name: "Sleep Calculator", slug: "sleep-calculator", description: "Find optimal bedtime or wake time based on 90-minute sleep cycles", category: "health", icon: "😴", keywords: ["sleep", "calculator", "bedtime", "wake up", "sleep cycle", "90 minutes"] },
  { name: "Blood Pressure Checker", slug: "blood-pressure-checker", description: "Check blood pressure category: Normal, Elevated, Stage 1/2 Hypertension", category: "health", icon: "🩺", keywords: ["blood pressure", "bp", "systolic", "diastolic", "hypertension", "normal"] },
  { name: "Menstrual Cycle Calculator", slug: "menstrual-cycle-calculator", description: "Track menstrual cycle, fertile window, ovulation day with calendar view", category: "health", icon: "🌸", keywords: ["menstrual", "period", "cycle", "fertile", "ovulation", "calendar"] },

  // Real Estate Tools
  { name: "Plot Area Calculator", slug: "plot-area-calculator", description: "Calculate plot area in sq ft, sq m, acres, bigha, guntha and cents", category: "realestate", icon: "📐", keywords: ["plot area", "land area", "sq ft", "bigha", "guntha", "cents", "acres"] },
  { name: "Paint Calculator", slug: "paint-calculator", description: "Calculate paint needed for rooms with doors, windows and cost estimate", category: "realestate", icon: "🎨", keywords: ["paint", "calculator", "room", "walls", "liters", "cost", "interior"] },
  { name: "Tile Calculator", slug: "tile-calculator", description: "Calculate tiles needed for a room with wastage buffer and cost estimate", category: "realestate", icon: "🪟", keywords: ["tile", "calculator", "flooring", "room", "wastage", "cost"] },
  { name: "Brick Calculator", slug: "brick-calculator", description: "Calculate bricks, cement bags and sand for wall construction", category: "realestate", icon: "🧱", keywords: ["brick", "calculator", "wall", "cement", "sand", "mortar", "construction"] },
  { name: "Cement Calculator", slug: "cement-calculator", description: "Calculate cement, sand and aggregate for plastering, brickwork and concrete", category: "realestate", icon: "🏗️", keywords: ["cement", "calculator", "concrete", "plastering", "m20", "m25", "bags"] },
  { name: "Interior Cost Estimator", slug: "interior-cost-estimator", description: "Estimate interior design cost for rooms by city tier and quality level", category: "realestate", icon: "🏠", keywords: ["interior", "cost", "estimate", "bedroom", "kitchen", "bathroom", "design"] },

  // Electrical & Engineering (6)
  { name: "Wire Size Calculator", slug: "wire-size-calculator", description: "Calculate recommended wire size in sq mm for Indian standards based on current, voltage and cable length", category: "electrical", icon: "🔌", keywords: ["wire size", "cable", "sq mm", "copper", "aluminium", "current", "electrical"] },
  { name: "Voltage Drop Calculator", slug: "voltage-drop-calculator", description: "Calculate voltage drop percentage for cables and check if within 3% Indian standard limit", category: "electrical", icon: "📉", keywords: ["voltage drop", "cable", "wire", "percentage", "electrical", "acceptable"] },
  { name: "Power Consumption Calculator", slug: "power-consumption-calculator", description: "Calculate monthly electricity consumption and cost for all home appliances", category: "electrical", icon: "💡", keywords: ["power consumption", "electricity", "kwh", "appliance", "monthly bill", "watt"] },
  { name: "Ohm's Law Calculator", slug: "ohms-law-calculator", description: "Calculate voltage, current, resistance and power using Ohm's law - enter any 2 values", category: "electrical", icon: "⚡", keywords: ["ohms law", "voltage", "current", "resistance", "power", "formula"] },
  { name: "Transformer Calculator", slug: "transformer-calculator", description: "Calculate transformer turns ratio, secondary voltage/turns and power transfer", category: "electrical", icon: "🔄", keywords: ["transformer", "turns ratio", "primary", "secondary", "voltage", "step down", "step up"] },
  { name: "Solar Panel Calculator", slug: "solar-panel-calculator", description: "Calculate solar panel system size, cost, savings and payback period for Indian cities", category: "electrical", icon: "☀️", keywords: ["solar panel", "solar", "rooftop", "kw", "savings", "payback", "renewable"] },

  // Cooking & Kitchen (5)
  { name: "Recipe Unit Converter", slug: "recipe-unit-converter", description: "Convert between cups, tablespoons, teaspoons, grams, ml with ingredient-specific densities", category: "cooking", icon: "🥄", keywords: ["recipe", "convert", "cups", "tablespoon", "teaspoon", "grams", "ml", "cooking"] },
  { name: "Cooking Time Calculator", slug: "cooking-time-calculator", description: "Get cooking times for Indian dishes across pressure cooker, microwave, oven and stovetop", category: "cooking", icon: "⏲️", keywords: ["cooking time", "pressure cooker", "microwave", "oven", "recipe", "how long"] },
  { name: "Indian Food Calorie Counter", slug: "indian-food-calorie-counter", description: "Track calories, protein, carbs and fat for 100+ Indian foods with meal tracker", category: "cooking", icon: "🍛", keywords: ["calorie", "indian food", "nutrition", "protein", "carbs", "fat", "diet", "meal"] },
  { name: "Gas Cylinder Calculator", slug: "gas-cylinder-calculator", description: "Calculate how long a 14.2kg LPG cylinder lasts and compare with induction cooking cost", category: "cooking", icon: "🔥", keywords: ["gas cylinder", "lpg", "cooking gas", "14.2 kg", "induction", "monthly cost"] },
  { name: "Water TDS Calculator", slug: "water-tds-calculator", description: "Check water TDS quality classification and get purifier recommendation (UV, RO, RO+UV)", category: "cooking", icon: "💧", keywords: ["tds", "water quality", "purifier", "ro", "uv", "ppm", "drinking water"] },

  // Wedding & Events (5)
  { name: "Wedding Budget Calculator", slug: "wedding-budget-calculator", description: "Plan wedding budget with auto-allocation for venue, catering, decoration and per-plate estimate", category: "wedding", icon: "💰", keywords: ["wedding budget", "shaadi", "budget planner", "venue", "catering", "per plate"] },
  { name: "Guest List Manager", slug: "guest-list-manager", description: "Manage wedding guest list with RSVP tracking, categories, side filters and text export", category: "wedding", icon: "📋", keywords: ["guest list", "wedding guests", "rsvp", "bride", "groom", "invite list"] },
  { name: "Wedding Date Finder", slug: "wedding-date-finder", description: "Find auspicious wedding dates (Shubh Muhurat) based on Hindu Panchang for 2025-2027", category: "wedding", icon: "📅", keywords: ["shubh muhurat", "wedding date", "auspicious", "purnima", "hindu calendar", "nakshatra"] },
  { name: "Gift Registry Calculator", slug: "gift-registry-calculator", description: "Estimate wedding gifts by guest category and calculate return gift budget", category: "wedding", icon: "🎁", keywords: ["wedding gift", "shagun", "gift estimate", "return gift", "registry", "guest gift"] },
  { name: "Event Checklist Generator", slug: "event-checklist-generator", description: "Generate comprehensive event checklist with timeline for wedding, birthday, engagement and more", category: "wedding", icon: "✅", keywords: ["event checklist", "wedding checklist", "birthday", "engagement", "housewarming", "planning"] },

  // Agriculture (6)
  { name: "Crop Yield Calculator", slug: "crop-yield-calculator", description: "Calculate expected crop yield, revenue and profit for rice, wheat, sugarcane, cotton and more", category: "agriculture", icon: "🌾", keywords: ["crop yield", "harvest", "msp", "quintal", "rice", "wheat", "farming"] },
  { name: "Fertilizer Calculator", slug: "fertilizer-calculator", description: "Calculate NPK fertilizer requirement with Urea, DAP, MOP quantities and application schedule", category: "agriculture", icon: "🧪", keywords: ["fertilizer", "urea", "dap", "mop", "npk", "nitrogen", "phosphorus", "potassium"] },
  { name: "Land Measurement Converter", slug: "land-measurement-converter", description: "Convert between Acre, Hectare, Bigha, Guntha, Cent, Kanal, Marla, Biswa, Katha and more Indian land units", category: "agriculture", icon: "📐", keywords: ["land measurement", "bigha", "guntha", "acre", "hectare", "kanal", "marla", "biswa", "katha"] },
  { name: "Irrigation Calculator", slug: "irrigation-calculator", description: "Calculate water requirement, irrigation schedule, pump capacity and electricity cost for crops", category: "agriculture", icon: "💧", keywords: ["irrigation", "water requirement", "pump", "hp", "crop water", "schedule", "electricity"] },
  { name: "Farm Profit Calculator", slug: "farm-profit-calculator", description: "Calculate farm profit with detailed cost breakdown for seeds, fertilizer, labor, irrigation and transport", category: "agriculture", icon: "📊", keywords: ["farm profit", "agriculture profit", "cost of cultivation", "roi", "farming income"] },
  { name: "Seed Rate Calculator", slug: "seed-rate-calculator", description: "Calculate seed requirement per crop with germination rate adjustment, spacing info and cost estimate", category: "agriculture", icon: "🌱", keywords: ["seed rate", "sowing", "germination", "seed cost", "kg per acre", "spacing"] },

  // Exam & Competitive (8)
  { name: "Marks Percentage Calculator", slug: "marks-percentage-calculator", description: "Calculate percentage, grade and pass/fail status for single or multiple subjects", category: "exam", icon: "📊", keywords: ["marks", "percentage", "grade", "pass", "fail", "result", "exam"] },
  { name: "NEET Score Predictor", slug: "neet-score-predictor", description: "Predict NEET score, percentile and expected college category from correct/wrong answers", category: "exam", icon: "🏥", keywords: ["neet", "medical", "score", "percentile", "cutoff", "mbbs", "aiims"] },
  { name: "JEE Rank Predictor", slug: "jee-rank-predictor", description: "Predict JEE Main rank and percentile with IIT/NIT/IIIT cutoff reference", category: "exam", icon: "🎯", keywords: ["jee", "main", "rank", "percentile", "iit", "nit", "iiit", "josaa"] },
  { name: "GATE Score Calculator", slug: "gate-score-calculator", description: "Calculate GATE score, qualifying status and PSU cutoff comparison", category: "exam", icon: "🎓", keywords: ["gate", "score", "psu", "iocl", "ntpc", "qualifying", "mtech"] },
  { name: "CAT Percentile Calculator", slug: "cat-percentile-calculator", description: "Estimate CAT percentile from section-wise scores with IIM cutoff reference", category: "exam", icon: "📈", keywords: ["cat", "percentile", "iim", "mba", "varc", "dilr", "quant"] },
  { name: "Board Percentage Calculator", slug: "board-percentage-calculator", description: "Calculate board exam percentage, CGPA, best-of-5 for CBSE/ICSE/State boards", category: "exam", icon: "📝", keywords: ["board", "cbse", "icse", "percentage", "cgpa", "10th", "12th", "result"] },
  { name: "Scholarship Eligibility Checker", slug: "scholarship-eligibility-checker", description: "Check eligibility for Indian scholarships - NSP, INSPIRE, Post-Matric and more", category: "exam", icon: "🏆", keywords: ["scholarship", "nsp", "inspire", "kvpy", "post matric", "merit", "eligibility"] },
  { name: "College Fee Calculator", slug: "college-fee-calculator", description: "Estimate college fees for IIT/NIT/Medical/MBA with education loan EMI calculator", category: "exam", icon: "🏫", keywords: ["college", "fee", "iit", "nit", "medical", "iim", "education loan", "emi"] },

  // Vehicle & Transport (6)
  { name: "Mileage Calculator", slug: "mileage-calculator", description: "Calculate vehicle mileage (km/l), cost per km and compare with claimed mileage", category: "vehicle", icon: "⛽", keywords: ["mileage", "km per liter", "fuel efficiency", "petrol", "diesel", "cng"] },
  { name: "Road Trip Planner", slug: "road-trip-planner", description: "Plan road trips with fuel cost, time estimate, toll and per-person cost split", category: "vehicle", icon: "🗺️", keywords: ["road trip", "fuel cost", "distance", "toll", "travel", "trip planner"] },
  { name: "Car Insurance Estimator", slug: "car-insurance-estimator", description: "Estimate car insurance premium with IDV, third-party and comprehensive breakdown", category: "vehicle", icon: "🛡️", keywords: ["car insurance", "premium", "idv", "third party", "comprehensive", "irdai"] },
  { name: "Tyre Size Calculator", slug: "tyre-size-calculator", description: "Parse tyre markings, calculate dimensions and compare two tyre sizes side by side", category: "vehicle", icon: "🛞", keywords: ["tyre", "tire", "size", "width", "aspect ratio", "rim", "diameter"] },
  { name: "Vehicle Depreciation Calculator", slug: "vehicle-depreciation-calculator", description: "Calculate vehicle depreciation using Written Down Value method with year-wise table", category: "vehicle", icon: "📉", keywords: ["depreciation", "vehicle value", "wdv", "resale", "car value", "bike value"] },
  { name: "Toll Calculator", slug: "toll-calculator", description: "Estimate toll charges for Indian highways and expressways by vehicle type", category: "vehicle", icon: "🛣️", keywords: ["toll", "highway", "expressway", "fastag", "nhai", "toll plaza", "toll rate"] },

  // Astrology & Spiritual
  { name: "Kundli Calculator", slug: "kundli-calculator", description: "Generate basic Kundli with Sun sign, Moon sign (Rashi), ruling planet, element & compatibility", category: "astrology", icon: "🪐", keywords: ["kundli", "janam kundli", "birth chart", "horoscope", "sun sign", "moon sign", "vedic astrology"] },
  { name: "Rashi Calculator", slug: "rashi-calculator", description: "Find your Rashi (zodiac sign) by date of birth or name letter with personality traits", category: "astrology", icon: "♈", keywords: ["rashi", "zodiac", "mesh", "vrishabh", "mithun", "kark", "simha", "kanya", "tula", "vrishchik"] },
  { name: "Nakshatra Calculator", slug: "nakshatra-calculator", description: "Find your birth Nakshatra (star) with deity, symbol & compatible nakshatras", category: "astrology", icon: "⭐", keywords: ["nakshatra", "birth star", "ashwini", "rohini", "pushya", "hasta", "27 nakshatras", "vedic"] },
  { name: "Panchang Calculator", slug: "panchang-calculator", description: "Get daily Panchang with Tithi, Nakshatra, Yoga, Karana & Vaar for any date", category: "astrology", icon: "📅", keywords: ["panchang", "tithi", "yoga", "karana", "vaar", "hindu calendar", "auspicious", "shubh muhurat"] },
  { name: "Name Numerology Calculator", slug: "name-numerology-calculator", description: "Calculate Destiny, Soul & Personality numbers from name using Chaldean numerology", category: "astrology", icon: "🔢", keywords: ["numerology", "name numerology", "destiny number", "soul number", "chaldean", "life path"] },
  { name: "Gemstone Recommendation", slug: "gemstone-recommendation", description: "Get recommended gemstone based on Rashi with weight, metal, finger & mantra details", category: "astrology", icon: "💎", keywords: ["gemstone", "ratna", "neelam", "panna", "manik", "pukhraj", "moti", "moonga", "heera"] },

  // Banking & Finance (additional)
  { name: "FD Comparison", slug: "fd-comparison", description: "Compare Fixed Deposit rates across 10 major Indian banks with maturity calculator", category: "finance", icon: "🏦", keywords: ["fd comparison", "fixed deposit", "bank comparison", "best fd rate", "sbi", "hdfc", "icici"] },
  { name: "Credit Score Estimator", slug: "credit-score-estimator", description: "Estimate your CIBIL credit score based on payment history, utilization & credit mix", category: "finance", icon: "📊", keywords: ["credit score", "cibil", "cibil score", "credit rating", "750", "credit report"] },
  { name: "Loan Eligibility Calculator", slug: "loan-eligibility-calculator", description: "Calculate maximum loan amount eligible based on income, existing EMIs & loan type", category: "finance", icon: "✅", keywords: ["loan eligibility", "home loan eligibility", "personal loan", "car loan", "max loan amount"] },
  { name: "SWP Calculator", slug: "swp-calculator", description: "Calculate Systematic Withdrawal Plan - how long your corpus lasts with monthly withdrawals", category: "finance", icon: "💸", keywords: ["swp", "systematic withdrawal", "retirement", "corpus", "monthly income", "withdrawal plan"] },
  { name: "ELSS Tax Calculator", slug: "elss-tax-calculator", description: "Calculate ELSS returns with tax savings under 80C and compare with Fixed Deposits", category: "finance", icon: "🛡️", keywords: ["elss", "tax saving", "80c", "mutual fund", "tax benefit", "equity linked"] },
  { name: "Pension Calculator", slug: "pension-calculator", description: "Compare Old Pension Scheme (OPS) vs New Pension Scheme (NPS) with detailed breakdown", category: "finance", icon: "👴", keywords: ["pension", "ops", "nps", "retirement", "old pension", "new pension", "government pension"] },

  // Legal & Government (5)
  { name: "Court Fee Calculator", slug: "court-fee-calculator", description: "Calculate court fees, stamp duty and advocate fee estimates for 15 Indian states", category: "legal", icon: "🏛️", keywords: ["court fee", "stamp duty", "advocate fee", "civil suit", "property case", "consumer court", "legal fees"] },
  { name: "Legal Notice Generator", slug: "legal-notice-generator", description: "Generate formatted legal notice templates for cheque bounce, eviction, recovery and more", category: "legal", icon: "📜", keywords: ["legal notice", "cheque bounce", "section 138", "eviction", "recovery", "defamation", "consumer complaint"] },
  { name: "RTI Application Generator", slug: "rti-application-generator", description: "Generate RTI application under Section 6 of RTI Act 2005 for central and state government", category: "legal", icon: "📋", keywords: ["rti", "right to information", "rti act", "section 6", "pio", "public information", "government"] },
  { name: "Affidavit Generator", slug: "affidavit-generator", description: "Generate affidavits for name change, address proof, income declaration and self declaration", category: "legal", icon: "📝", keywords: ["affidavit", "name change", "address proof", "income declaration", "self declaration", "notary", "stamp paper"] },
  { name: "Voter ID Info", slug: "voter-id-info", description: "Validate EPIC number format, parse state codes and check voter ID status information", category: "legal", icon: "🗳️", keywords: ["voter id", "epic", "election", "nvsp", "voter card", "electoral", "state code"] },

  // Additional tools in existing categories
  { name: "Indian Calendar", slug: "indian-calendar", description: "Monthly calendar with Indian national holidays, festivals and bank holidays color-coded", category: "datetime", icon: "📅", keywords: ["indian calendar", "holidays", "festivals", "diwali", "holi", "bank holiday", "national holiday", "pongal", "onam"] },
  { name: "Unit Price Calculator", slug: "unit-price-calculator", description: "Compare product prices per unit to find best value for grocery shopping", category: "math", icon: "🛒", keywords: ["unit price", "price comparison", "grocery", "best value", "price per kg", "price per liter"] },
  { name: "EMI Bridge Calculator", slug: "emi-bridge-calculator", description: "Compare loan balance transfer costs and savings between old and new bank", category: "finance", icon: "🔄", keywords: ["balance transfer", "emi bridge", "loan transfer", "interest savings", "processing fee", "home loan transfer"] },
  { name: "Split Bill Calculator", slug: "split-bill-calculator", description: "Split bills equally or by items with tip calculation and UPI-friendly rounding", category: "fun", icon: "🧾", keywords: ["split bill", "bill splitter", "share bill", "restaurant", "upi", "group expense", "itemized split"] },
  { name: "Age on Planet Calculator", slug: "age-on-planet-calculator", description: "Find your age on every planet using actual orbital periods with fun facts", category: "fun", icon: "🪐", keywords: ["planet age", "space", "mercury", "venus", "mars", "jupiter", "saturn", "orbital period", "solar system"] },

  // AI Writing Tools (16)
  { name: "AI Paragraph Rewriter", slug: "ai-paragraph-rewriter", description: "Rewrite paragraphs in Formal, Casual or Concise tone using synonym mapping and sentence restructuring", category: "ai", icon: "✍️", keywords: ["paragraph rewriter", "rewrite", "paraphrase", "rephrase", "synonym", "reword", "ai writer"] },
  { name: "AI Text Summarizer", slug: "ai-text-summarizer", description: "Summarize long text into key sentences using extractive summarization with word count reduction", category: "ai", icon: "📋", keywords: ["summarize", "summary", "text summary", "extractive", "condense", "shorten", "tldr"] },
  { name: "AI Story Generator", slug: "ai-story-generator", description: "Generate short stories in Adventure, Romance, Mystery, SciFi, Horror or Comedy genres", category: "ai", icon: "📖", keywords: ["story generator", "short story", "fiction", "creative writing", "adventure", "romance", "mystery"] },
  { name: "AI Email Writer", slug: "ai-email-writer", description: "Generate professional emails for job applications, leave requests, complaints, thank you & more", category: "ai", icon: "📧", keywords: ["email writer", "professional email", "job application", "leave request", "complaint", "thank you email"] },
  { name: "AI Bio Generator", slug: "ai-bio-generator", description: "Generate professional bios for LinkedIn, Twitter, Instagram & Resume in multiple tones", category: "ai", icon: "👤", keywords: ["bio generator", "linkedin bio", "twitter bio", "instagram bio", "professional bio", "about me"] },
  { name: "AI Slogan Generator", slug: "ai-slogan-generator", description: "Generate 10 creative slogan variations for brands using rhyming, alliteration & emotional hooks", category: "ai", icon: "💡", keywords: ["slogan generator", "tagline", "brand slogan", "catchphrase", "motto", "marketing"] },
  { name: "AI Blog Title Generator", slug: "ai-blog-title-generator", description: "Generate 15 blog title variations using proven formulas for How-to, Lists, Guides & Reviews", category: "ai", icon: "📰", keywords: ["blog title", "headline generator", "title ideas", "blog post", "seo title", "content ideas"] },
  { name: "AI Cover Letter Generator", slug: "ai-cover-letter-generator", description: "Generate professional 4-paragraph cover letters tailored to job title, company & skills", category: "ai", icon: "📄", keywords: ["cover letter", "job application", "professional letter", "hiring", "resume", "career"] },
  { name: "AI Resume Bullet Points", slug: "ai-resume-bullet-points", description: "Transform job descriptions into achievement-oriented resume bullet points with action verbs", category: "ai", icon: "🎯", keywords: ["resume", "bullet points", "action verbs", "achievements", "cv", "career", "job description"] },
  { name: "AI Product Description", slug: "ai-product-description", description: "Generate product descriptions in Short, Medium & Long formats with Professional, Casual or Luxury tone", category: "ai", icon: "🛍️", keywords: ["product description", "ecommerce", "copywriting", "marketing copy", "product listing"] },
  { name: "AI Social Caption Generator", slug: "ai-social-caption-generator", description: "Generate social media captions for Instagram, Facebook, Twitter & LinkedIn with hashtags", category: "ai", icon: "📱", keywords: ["social media caption", "instagram caption", "facebook post", "twitter", "linkedin", "hashtags"] },
  { name: "AI Thank You Note", slug: "ai-thank-you-note", description: "Generate thank you notes for gifts, interviews, weddings, business meetings & more occasions", category: "ai", icon: "🙏", keywords: ["thank you note", "gratitude", "appreciation", "thank you letter", "gift thanks", "interview thanks"] },
  { name: "AI Apology Letter", slug: "ai-apology-letter", description: "Generate sincere apology letters for late delivery, missed deadlines, mistakes & service issues", category: "ai", icon: "💌", keywords: ["apology letter", "sorry letter", "apologize", "mistake", "late delivery", "complaint response"] },
  { name: "AI Wedding Invitation", slug: "ai-wedding-invitation", description: "Generate wedding invitations in Hindu, Modern, Muslim, Sikh & Christian styles with Hindi/English", category: "ai", icon: "💒", keywords: ["wedding invitation", "shaadi card", "nikah", "anand karaj", "marriage invitation", "wedding card"] },
  { name: "AI YouTube Script Outline", slug: "ai-youtube-script-outline", description: "Generate structured YouTube video script outlines with hooks, main points, CTA & time estimates", category: "ai", icon: "🎬", keywords: ["youtube script", "video outline", "content creation", "youtube", "script writing", "video planning"] },
  { name: "AI Interview Questions", slug: "ai-interview-questions", description: "Generate 20 interview questions for 8 roles across Fresher, Mid-level & Senior with answer hints", category: "ai", icon: "🎤", keywords: ["interview questions", "job interview", "hr questions", "behavioral", "technical", "situational"] },
  { name: "AI Essay Writer", slug: "ai-essay-writer", description: "Generate structured essays in Argumentative, Descriptive, Narrative, Expository & Persuasive styles", category: "ai", icon: "📝", keywords: ["essay writer", "essay generator", "argumentative essay", "descriptive essay", "narrative essay", "school essay", "college essay"] },
  { name: "AI Paragraph Completer", slug: "ai-paragraph-completer", description: "Complete incomplete paragraphs with 3 continuation options - natural flow, add detail, or conclude", category: "ai", icon: "📄", keywords: ["paragraph completer", "continue writing", "text completion", "paragraph generator", "writing assistant"] },
  { name: "AI Article Outline Generator", slug: "ai-article-outline-generator", description: "Generate article outlines with title suggestions, H2/H3 headings for how-to, guide, listicle & review", category: "ai", icon: "📑", keywords: ["article outline", "blog outline", "content structure", "headings generator", "article planner", "content planning"] },
  { name: "AI Poem Generator", slug: "ai-poem-generator", description: "Generate poems in Haiku, Limerick, Sonnet, Free Verse, Rhyming & Acrostic styles with mood selection", category: "ai", icon: "🎭", keywords: ["poem generator", "haiku", "sonnet", "limerick", "rhyming poem", "acrostic", "poetry", "verse"] },
  { name: "AI Formal Letter Writer", slug: "ai-formal-letter-writer", description: "Generate formal letters for applications, requests, complaints, NOC, transfer & experience certificate", category: "ai", icon: "✉️", keywords: ["formal letter", "application letter", "request letter", "complaint letter", "NOC letter", "official letter"] },
  { name: "AI Speech Writer", slug: "ai-speech-writer", description: "Generate speeches for welcome, farewell, motivational, Independence Day, Teachers Day & graduation", category: "ai", icon: "🎙️", keywords: ["speech writer", "welcome speech", "farewell speech", "motivational speech", "independence day speech", "annual day"] },
  { name: "AI Hashtag Generator Pro", slug: "ai-hashtag-generator-pro", description: "Generate 30 hashtags in 3 tiers (Popular, Medium, Niche) for Instagram, Twitter, LinkedIn & TikTok", category: "ai", icon: "#️⃣", keywords: ["hashtag generator", "instagram hashtags", "twitter hashtags", "tiktok hashtags", "linkedin hashtags", "trending hashtags"] },
  { name: "AI Ad Copy Generator", slug: "ai-ad-copy-generator", description: "Generate ad copy for Google Ads, Facebook, Instagram & email with character count validation", category: "ai", icon: "📢", keywords: ["ad copy", "google ads", "facebook ad", "instagram caption", "email subject", "advertising", "copywriting"] },
  { name: "AI Meta Description Generator", slug: "ai-meta-description-generator", description: "Generate 5 SEO meta descriptions with character count indicator for blog, product, service & tool pages", category: "ai", icon: "🔍", keywords: ["meta description", "seo description", "page description", "search snippet", "serp", "meta tag"] },
  { name: "AI LinkedIn Post Generator", slug: "ai-linkedin-post-generator", description: "Generate LinkedIn posts with hook, body, hashtags & CTA for achievements, insights, stories & announcements", category: "ai", icon: "💼", keywords: ["linkedin post", "linkedin content", "professional post", "linkedin engagement", "networking post"] },
  { name: "AI WhatsApp Message Writer", slug: "ai-whatsapp-message-writer", description: "Generate WhatsApp messages for festivals, birthdays, anniversaries, condolences & business in 3 lengths", category: "ai", icon: "💬", keywords: ["whatsapp message", "festival greeting", "birthday message", "diwali wishes", "holi wishes", "eid mubarak"] },
  { name: "AI Complaint Letter Generator", slug: "ai-complaint-letter-generator", description: "Generate formal complaint letters for product defects, billing errors, service issues & insurance claims", category: "ai", icon: "⚠️", keywords: ["complaint letter", "formal complaint", "consumer complaint", "product defect", "billing error", "grievance letter"] },
  { name: "AI Birthday Wish Generator", slug: "ai-birthday-wish-generator", description: "Generate 5 birthday wishes in Short, Medium, Long, Poem & WhatsApp styles for any relationship and tone", category: "ai", icon: "🎂", keywords: ["birthday wish", "birthday message", "happy birthday", "birthday greeting", "birthday card", "birthday poem"] },
  { name: "AI Love Letter Generator", slug: "ai-love-letter-generator", description: "Generate romantic love letters in Poetic, Heartfelt & Playful tones with memories and future together", category: "ai", icon: "💕", keywords: ["love letter", "romantic letter", "valentine", "love message", "romantic writing", "love note"] },
  { name: "AI Breakup Text Generator", slug: "ai-breakup-text-generator", description: "Generate breakup messages in Kind, Direct, Humorous & Mature tones as text, letter or email", category: "ai", icon: "💔", keywords: ["breakup text", "breakup message", "breakup letter", "ending relationship", "breakup email"] },
  { name: "AI Pickup Line Generator", slug: "ai-pickup-line-generator", description: "Generate 10 pickup lines in Cheesy, Smooth, Nerdy, Funny, Romantic & Bollywood styles from 50+ per category", category: "ai", icon: "😏", keywords: ["pickup lines", "flirting", "rizz", "cheesy lines", "smooth lines", "bollywood pickup"] },
  { name: "AI Rap Lyrics Generator", slug: "ai-rap-lyrics-generator", description: "Generate rap lyrics with 2 verses and chorus in Motivational, Street & Bollywood styles with AABB rhyme", category: "ai", icon: "🎤", keywords: ["rap lyrics", "rap generator", "hip hop", "freestyle", "verse", "chorus", "rhyme"] },
  { name: "AI Motivational Quote Generator", slug: "ai-motivational-quote-generator", description: "Generate 10 motivational quotes on Success, Hustle, Love, Life, Education, Health, Leadership & Friendship", category: "ai", icon: "💪", keywords: ["motivational quotes", "inspiration", "success quotes", "life quotes", "hustle quotes", "daily motivation"] },
  { name: "AI Tone Changer", slug: "ai-tone-changer", description: "Transform text tone to Professional, Casual, Friendly, Formal, Persuasive, Academic or Humorous with synonym replacement", category: "ai", icon: "🔄", keywords: ["tone changer", "text tone", "rewrite tone", "professional tone", "casual tone", "formal tone"] },
  { name: "AI Bullets to Paragraph", slug: "ai-bullets-to-paragraph", description: "Convert bullet points into flowing paragraphs in Narrative, Professional & Academic styles with transitions", category: "ai", icon: "📝", keywords: ["bullets to paragraph", "bullet points", "paragraph converter", "text converter", "writing tool"] },
  { name: "AI Paragraph to Bullets", slug: "ai-paragraph-to-bullets", description: "Extract key points from paragraphs as Brief, Detailed or Action-oriented bullet points with copy options", category: "ai", icon: "📋", keywords: ["paragraph to bullets", "extract bullets", "key points", "summarize", "bullet points"] },
  { name: "AI Text Expander", slug: "ai-text-expander", description: "Expand short text by 50%, 100% or 200% with descriptive adjectives, elaborations and examples", category: "ai", icon: "📐", keywords: ["text expander", "expand text", "make text longer", "elaborate", "add detail", "word count"] },
  { name: "AI Cold Email Generator", slug: "ai-cold-email-generator", description: "Generate 3 cold email versions - Direct, Curiosity-based & Value-first with subject lines and pro tips", category: "ai", icon: "📨", keywords: ["cold email", "outreach email", "sales email", "business email", "email template", "prospecting"] },
  { name: "AI Testimonial Generator", slug: "ai-testimonial-generator", description: "Generate customer testimonials in Short, Medium & Detailed formats with star ratings and customer names", category: "ai", icon: "⭐", keywords: ["testimonial generator", "review generator", "customer review", "product review", "social proof"] },
  { name: "AI Press Release Generator", slug: "ai-press-release-generator", description: "Generate press releases for Product Launch, Partnership, Award, Milestone & Event with proper formatting", category: "ai", icon: "📰", keywords: ["press release", "media release", "news release", "PR", "announcement", "media kit"] },
  { name: "AI About Us Generator", slug: "ai-about-us-generator", description: "Generate professional About Us page content for your company in Professional, Friendly & Story-based styles", category: "ai", icon: "🏢", keywords: ["about us generator", "company description", "about page", "business bio", "company profile"] },
  { name: "AI Assignment Helper", slug: "ai-assignment-helper", description: "Get structured outlines, key points and reference suggestions for school & college assignments", category: "ai", icon: "📚", keywords: ["assignment helper", "homework help", "essay outline", "assignment outline", "student helper"] },
  { name: "AI Explain Simply", slug: "ai-explain-simply", description: "Simplify complex topics into easy-to-understand language at ELI5, ELI10 & Simple Adult levels", category: "ai", icon: "💡", keywords: ["explain simply", "simplify text", "eli5", "easy explanation", "simple language"] },
  { name: "AI Flashcard Generator", slug: "ai-flashcard-generator", description: "Generate study flashcards from any topic or notes with flip animation and progress tracking", category: "ai", icon: "🃏", keywords: ["flashcard generator", "study cards", "revision cards", "memory cards", "exam prep"] },
  { name: "AI Job Description Generator", slug: "ai-job-description-generator", description: "Generate professional job descriptions with responsibilities, requirements and benefits for any role", category: "ai", icon: "💼", keywords: ["job description", "JD generator", "hiring", "recruitment", "job posting"] },
  { name: "AI Math Solver", slug: "ai-math-solver", description: "Solve math problems step-by-step including arithmetic, algebra, quadratic equations and geometry", category: "ai", icon: "🧮", keywords: ["math solver", "equation solver", "algebra solver", "math calculator", "step by step math"] },
  { name: "AI Meeting Notes Summarizer", slug: "ai-meeting-notes-summarizer", description: "Extract key decisions, action items and next steps from meeting notes automatically", category: "ai", icon: "📋", keywords: ["meeting notes", "meeting summary", "action items", "meeting minutes", "notes summarizer"] },
  { name: "AI Quiz Generator", slug: "ai-quiz-generator", description: "Generate MCQ, True/False and Fill-in-the-blank quizzes for any topic with answer keys and timer", category: "ai", icon: "❓", keywords: ["quiz generator", "question generator", "MCQ generator", "test maker", "exam questions"] },
  { name: "AI Study Notes Generator", slug: "ai-study-notes-generator", description: "Generate structured study notes with key concepts, definitions, formulas and revision points", category: "ai", icon: "📓", keywords: ["study notes", "revision notes", "key points", "study material", "exam notes"] },
];

export function getToolsByCategory(categorySlug: string): Tool[] {
  return tools.filter((t) => t.category === categorySlug);
}

export function getToolBySlug(slug: string): Tool | undefined {
  return tools.find((t) => t.slug === slug);
}

export function searchTools(query: string): Tool[] {
  const q = query.toLowerCase();
  return tools.filter(
    (t) =>
      t.name.toLowerCase().includes(q) ||
      t.description.toLowerCase().includes(q) ||
      t.keywords.some((k) => k.includes(q))
  );
}
