"use client";
import { useState } from "react";

type Role = "Software Engineer" | "Data Analyst" | "Marketing" | "Sales" | "HR" | "Finance" | "Product Manager" | "Designer";
type Level = "Fresher" | "Mid-level" | "Senior";

const roles: Role[] = ["Software Engineer", "Data Analyst", "Marketing", "Sales", "HR", "Finance", "Product Manager", "Designer"];
const levels: Level[] = ["Fresher", "Mid-level", "Senior"];

interface Question { q: string; hint: string }

const questionBank: Record<Role, Record<"technical" | "behavioral" | "situational" | "hr", Record<Level, Question[]>>> = {
  "Software Engineer": {
    technical: {
      Fresher: [
        { q: "Explain the difference between stack and queue data structures.", hint: "Define both, explain LIFO vs FIFO, give real-world examples." },
        { q: "What is Object-Oriented Programming? Name its four pillars.", hint: "Encapsulation, Inheritance, Polymorphism, Abstraction with examples." },
        { q: "What is the difference between == and === in JavaScript?", hint: "Type coercion vs strict comparison, give edge case examples." },
        { q: "Explain RESTful APIs and HTTP methods (GET, POST, PUT, DELETE).", hint: "Define REST principles, explain each method with use cases." },
        { q: "What is version control? How does Git work?", hint: "Explain branching, commits, merging, and common Git workflows." },
      ],
      "Mid-level": [
        { q: "Explain microservices architecture and how it differs from monolithic.", hint: "Compare both, discuss pros/cons, when to use each." },
        { q: "How would you optimize a slow SQL query?", hint: "Indexing, query analysis, EXPLAIN plan, normalization vs denormalization." },
        { q: "Describe SOLID principles with examples.", hint: "Single Responsibility, Open/Closed, Liskov, Interface Segregation, Dependency Inversion." },
        { q: "How do you handle state management in large frontend applications?", hint: "Redux/Context API/Zustand, discuss patterns and trade-offs." },
        { q: "Explain CI/CD pipelines and their importance.", hint: "Continuous Integration/Deployment, tools, testing stages, rollback strategies." },
      ],
      Senior: [
        { q: "How would you design a system to handle 10 million concurrent users?", hint: "Load balancing, caching, database sharding, CDN, horizontal scaling." },
        { q: "Explain event-driven architecture and when you would choose it.", hint: "Message queues, event sourcing, CQRS, compare with request/response." },
        { q: "How do you approach technical debt in a growing codebase?", hint: "Identification, prioritization, refactoring strategies, balancing with features." },
        { q: "Describe your approach to mentoring junior developers.", hint: "Code reviews, pair programming, knowledge sharing, building culture." },
        { q: "How would you design a distributed caching system?", hint: "Redis/Memcached, cache invalidation, consistency, cache-aside vs write-through." },
      ],
    },
    behavioral: {
      Fresher: [
        { q: "Tell me about a challenging project you completed during college.", hint: "STAR: Situation, Task, Action, Result. Focus on problem-solving." },
        { q: "Describe a time you worked effectively in a team.", hint: "STAR: Show collaboration, communication, and your specific contribution." },
        { q: "How do you handle feedback on your code?", hint: "Show openness to learning, give examples of incorporating feedback." },
        { q: "Tell me about a time you had to learn a new technology quickly.", hint: "STAR: Demonstrate learning ability, resources used, outcome." },
        { q: "What motivates you to write clean code?", hint: "Discuss maintainability, team impact, professional pride, examples." },
      ],
      "Mid-level": [
        { q: "Describe a time you disagreed with a technical decision.", hint: "STAR: Show professional communication, data-driven approach, resolution." },
        { q: "Tell me about a time you had to deliver under a tight deadline.", hint: "STAR: Prioritization, communication, trade-offs, outcome." },
        { q: "How have you handled a bug in production?", hint: "STAR: Incident response, debugging approach, root cause analysis, prevention." },
        { q: "Describe a time you mentored or helped a colleague.", hint: "STAR: Show leadership, patience, knowledge sharing, impact." },
        { q: "Tell me about a time you had to refactor significant code.", hint: "STAR: Reasoning, approach, testing strategy, outcome." },
      ],
      Senior: [
        { q: "Describe a time you drove a major architectural decision.", hint: "STAR: Context, alternatives evaluated, stakeholder buy-in, outcome." },
        { q: "Tell me about a time you had to push back on unrealistic requirements.", hint: "STAR: Diplomatic communication, data-backed reasoning, compromise." },
        { q: "How have you built high-performing engineering teams?", hint: "STAR: Hiring, culture, processes, mentoring, measuring success." },
        { q: "Describe a significant failure and what you learned.", hint: "STAR: Honest assessment, root cause, actions taken, systemic changes." },
        { q: "Tell me about navigating competing priorities across teams.", hint: "STAR: Stakeholder management, prioritization framework, communication." },
      ],
    },
    situational: {
      Fresher: [
        { q: "If you found a critical bug right before release, what would you do?", hint: "Communicate immediately, assess severity, propose fix or delay." },
        { q: "How would you handle a task where requirements are unclear?", hint: "Ask clarifying questions, document assumptions, seek early feedback." },
        { q: "What would you do if you were stuck on a problem for hours?", hint: "Research, rubber duck debugging, ask for help, time-box efforts." },
        { q: "If a teammate's code is hard to understand, how would you address it?", hint: "Private conversation, focus on code not person, suggest improvements." },
        { q: "How would you handle being assigned a technology you've never used?", hint: "Research, tutorials, practice projects, ask team for guidance." },
      ],
      "Mid-level": [
        { q: "How would you handle a situation where two team members have conflicting approaches?", hint: "Facilitate discussion, evaluate trade-offs objectively, make data-driven decision." },
        { q: "If the PM wants a feature that is technically risky, what do you do?", hint: "Explain risks clearly, propose alternatives, document trade-offs." },
        { q: "How would you handle a legacy system that nobody wants to maintain?", hint: "Assess business value, create modernization plan, advocate for resources." },
        { q: "What would you do if your sprint goals seem unachievable?", hint: "Communicate early, reprioritize, negotiate scope, protect team." },
        { q: "How would you approach a performance issue reported by users?", hint: "Reproduce, profile, identify bottleneck, fix, monitor, prevent." },
      ],
      Senior: [
        { q: "How would you handle a team that is consistently missing deadlines?", hint: "Root cause analysis, process improvement, estimation techniques, morale." },
        { q: "If asked to migrate a critical system with zero downtime, how would you plan?", hint: "Blue-green deployment, feature flags, gradual migration, rollback plan." },
        { q: "How would you handle a disagreement with the CTO on technology choice?", hint: "Data-driven argument, prototype comparison, respect final decision." },
        { q: "What would you do if you discovered a security vulnerability in production?", hint: "Incident response, assess impact, patch urgently, post-mortem." },
        { q: "How would you decide between building vs buying a solution?", hint: "Cost analysis, time-to-market, maintenance burden, competitive advantage." },
      ],
    },
    hr: {
      Fresher: [
        { q: "Why did you choose software engineering as a career?", hint: "Genuine passion, problem-solving interest, specific inspiration story." },
        { q: "Where do you see yourself in 5 years?", hint: "Growth-oriented, specific technical or leadership aspirations." },
        { q: "What are your salary expectations?", hint: "Research market rates, give a range, express flexibility." },
        { q: "Why should we hire you over other candidates?", hint: "Unique strengths, relevant skills, cultural fit, enthusiasm." },
        { q: "Do you have any questions for us?", hint: "Ask about team culture, growth opportunities, tech stack, mentorship." },
      ],
      "Mid-level": [
        { q: "Why are you looking to leave your current company?", hint: "Focus on growth opportunities, new challenges, positive framing." },
        { q: "How do you stay updated with evolving technologies?", hint: "Blogs, conferences, side projects, communities, continuous learning." },
        { q: "What is your approach to work-life balance?", hint: "Boundaries, productivity, sustainable pace, flexibility." },
        { q: "Describe your ideal work environment.", hint: "Collaborative, growth-oriented, autonomous, match with company culture." },
        { q: "What is the most impactful project you have worked on?", hint: "STAR: Technical challenge, your role, measurable business impact." },
      ],
      Senior: [
        { q: "What leadership style do you follow?", hint: "Servant leadership, situational, examples of adapting style." },
        { q: "How do you handle stress and high-pressure situations?", hint: "Prioritization, delegation, maintaining calm, self-care." },
        { q: "What is your philosophy on building engineering culture?", hint: "Psychological safety, code reviews, learning, diversity." },
        { q: "Why are you interested in this specific role?", hint: "Research company, align with personal mission, specific excitement." },
        { q: "What would you do in your first 90 days?", hint: "Listen, learn, build relationships, quick wins, long-term strategy." },
      ],
    },
  },
  "Data Analyst": {
    technical: {
      Fresher: [
        { q: "What is the difference between SQL and NoSQL databases?", hint: "Structure, scalability, use cases, examples of each." },
        { q: "Explain the types of joins in SQL with examples.", hint: "INNER, LEFT, RIGHT, FULL, CROSS joins with diagram/example." },
        { q: "What is data cleaning and why is it important?", hint: "Missing values, duplicates, outliers, inconsistencies, impact on analysis." },
        { q: "Explain the difference between mean, median, and mode.", hint: "Definitions, when to use each, effect of outliers." },
        { q: "What tools have you used for data visualization?", hint: "Excel, Tableau, Power BI, Python (matplotlib/seaborn), specific examples." },
      ],
      "Mid-level": [
        { q: "How would you handle a dataset with 30% missing values?", hint: "Assess pattern, imputation methods, when to drop, impact on analysis." },
        { q: "Explain A/B testing and statistical significance.", hint: "Hypothesis testing, p-value, sample size, confidence intervals." },
        { q: "How do you design a dashboard for non-technical stakeholders?", hint: "KPIs, simplicity, storytelling, interactive filters, actionable insights." },
        { q: "What is the difference between correlation and causation?", hint: "Examples, confounding variables, how to establish causation." },
        { q: "Explain ETL processes and your experience with them.", hint: "Extract, Transform, Load, tools used, challenges, optimization." },
      ],
      Senior: [
        { q: "How would you build a data strategy for a growing company?", hint: "Data governance, infrastructure, team structure, tools, KPIs." },
        { q: "Explain how you would set up a data warehouse from scratch.", hint: "Architecture, star/snowflake schema, tools, ETL, governance." },
        { q: "How do you ensure data quality across multiple sources?", hint: "Validation rules, monitoring, reconciliation, governance framework." },
        { q: "Describe your approach to advanced predictive analytics.", hint: "ML integration, model selection, feature engineering, deployment." },
        { q: "How would you measure and communicate ROI of data initiatives?", hint: "Business metrics, before/after, cost-benefit, stakeholder presentation." },
      ],
    },
    behavioral: {
      Fresher: [
        { q: "Describe a data project you're most proud of.", hint: "STAR: Problem, approach, tools used, insights discovered, impact." },
        { q: "How do you handle ambiguous data requirements?", hint: "STAR: Ask questions, make assumptions, iterate, communicate." },
        { q: "Tell me about a time you presented data findings.", hint: "STAR: Audience, visualization choices, storytelling, outcome." },
        { q: "Describe a situation where data changed your initial assumption.", hint: "STAR: Open-mindedness, analytical rigor, updated conclusions." },
        { q: "How do you prioritize multiple data requests?", hint: "STAR: Urgency, impact, communication, time management." },
      ],
      "Mid-level": [
        { q: "Tell me about a time your analysis influenced a business decision.", hint: "STAR: Context, analysis approach, presentation, decision, impact." },
        { q: "Describe handling conflicting data from different sources.", hint: "STAR: Investigation, reconciliation, root cause, resolution." },
        { q: "How have you handled stakeholders who disagreed with your findings?", hint: "STAR: Data-backed defense, listening, collaborative resolution." },
        { q: "Tell me about automating a manual reporting process.", hint: "STAR: Problem identification, solution design, implementation, time saved." },
        { q: "Describe a time you had to explain complex analysis simply.", hint: "STAR: Audience awareness, analogies, visualizations, feedback." },
      ],
      Senior: [
        { q: "How have you built and led a data analytics team?", hint: "STAR: Hiring, training, culture, processes, outcomes." },
        { q: "Describe driving a data-driven culture in an organization.", hint: "STAR: Strategy, stakeholder buy-in, tools, training, results." },
        { q: "Tell me about a time you identified a major business opportunity through data.", hint: "STAR: Discovery, analysis, presentation, implementation, revenue impact." },
        { q: "How have you handled data privacy and compliance challenges?", hint: "STAR: GDPR/regulations, policy implementation, team training." },
        { q: "Describe navigating competing analytics priorities from leadership.", hint: "STAR: Framework, communication, trade-offs, stakeholder management." },
      ],
    },
    situational: {
      Fresher: [
        { q: "What would you do if your data source had unexpected format changes?", hint: "Investigate, adapt pipeline, communicate, add validation." },
        { q: "How would you handle a report deadline when data quality is poor?", hint: "Communicate limitations, clean what you can, note caveats." },
        { q: "If asked to prove a hypothesis you disagree with, what do you do?", hint: "Stay objective, let data speak, present findings honestly." },
        { q: "How would you approach analyzing a dataset you've never seen before?", hint: "EDA, understand schema, check quality, identify patterns." },
        { q: "What if a colleague is using data incorrectly in their presentation?", hint: "Private conversation, explain the issue, offer to help correct." },
      ],
      "Mid-level": [
        { q: "How would you handle a request for real-time analytics on legacy systems?", hint: "Assess feasibility, propose alternatives, incremental approach." },
        { q: "What would you do if your analysis deadline conflicts with data quality?", hint: "Communicate trade-offs, propose phased delivery, document limitations." },
        { q: "If leadership wanted a metric that could be misleading, what do you do?", hint: "Explain concerns, propose better metrics, educate on interpretation." },
        { q: "How would you handle discovering data that shows negative business results?", hint: "Present honestly, frame constructively, suggest actionable improvements." },
        { q: "What if different departments need contradictory data interpretations?", hint: "Standardize definitions, mediate, create single source of truth." },
      ],
      Senior: [
        { q: "How would you handle a data breach affecting your analytics pipeline?", hint: "Incident response, impact assessment, containment, communication." },
        { q: "If asked to reduce your team by 30%, how would you prioritize?", hint: "Business-critical functions, automation opportunities, cross-training." },
        { q: "How would you approach migrating analytics to a new platform?", hint: "Assessment, phased migration, parallel running, validation, training." },
        { q: "What if the CEO wants analytics that require accessing sensitive data?", hint: "Privacy assessment, anonymization, compliance, alternative approaches." },
        { q: "How would you handle analytics in a rapidly changing business environment?", hint: "Agile analytics, modular dashboards, flexible infrastructure." },
      ],
    },
    hr: {
      Fresher: [
        { q: "Why do you want to become a data analyst?", hint: "Genuine passion for data, problem-solving, specific inspiration." },
        { q: "Where do you see yourself in 5 years?", hint: "Senior analyst, data scientist, analytics leadership, continuous learning." },
        { q: "What are your salary expectations?", hint: "Research market rates, give a range, express flexibility." },
        { q: "Why should we hire you?", hint: "Analytical skills, tools proficiency, relevant projects, eagerness." },
        { q: "Do you have any questions for us?", hint: "Team structure, tools used, data maturity, growth opportunities." },
      ],
      "Mid-level": [
        { q: "Why are you looking for a change?", hint: "Growth, new challenges, skill development, positive framing." },
        { q: "How do you handle work pressure and tight deadlines?", hint: "Prioritization, time management, communication, examples." },
        { q: "What is your biggest professional achievement?", hint: "STAR: Significant impact, data-driven result, recognition." },
        { q: "How do you keep up with analytics trends?", hint: "Communities, courses, conferences, reading, experimentation." },
        { q: "Describe your ideal team and work environment.", hint: "Collaborative, data-driven culture, continuous learning." },
      ],
      Senior: [
        { q: "What is your management philosophy?", hint: "Empowerment, coaching, data-driven decisions, transparency." },
        { q: "How do you handle conflict in your team?", hint: "Listen, mediate, focus on facts, collaborative resolution." },
        { q: "What legacy do you want to leave at your next role?", hint: "Culture, processes, team growth, business impact." },
        { q: "Why this company specifically?", hint: "Company's data journey, challenges, alignment with goals." },
        { q: "What would you do in your first 90 days?", hint: "Assess, listen, quick wins, strategy, relationship building." },
      ],
    },
  },
  "Marketing": {
    technical: { Fresher: [{ q: "What is the marketing mix (4Ps)?", hint: "Product, Price, Place, Promotion with examples." }, { q: "Explain SEO and its importance.", hint: "On-page, off-page, technical SEO, organic traffic." }, { q: "What is the difference between branding and marketing?", hint: "Long-term vs short-term, identity vs promotion." }, { q: "How do you measure social media ROI?", hint: "Engagement, conversions, reach, cost per acquisition." }, { q: "What is content marketing?", hint: "Strategy, types of content, funnel stages, examples." }], "Mid-level": [{ q: "How do you build a comprehensive marketing strategy?", hint: "Market research, segmentation, positioning, channels, metrics." }, { q: "Explain marketing attribution models.", hint: "First-touch, last-touch, multi-touch, data-driven." }, { q: "How do you optimize conversion rates?", hint: "A/B testing, landing pages, CTA optimization, analytics." }, { q: "What is your approach to marketing automation?", hint: "Tools, workflows, segmentation, personalization, measurement." }, { q: "How do you balance brand building with performance marketing?", hint: "Budget allocation, metrics, long-term vs short-term." }], Senior: [{ q: "How do you develop a go-to-market strategy?", hint: "Market analysis, positioning, channels, pricing, launch plan." }, { q: "How do you manage marketing budget allocation across channels?", hint: "ROI analysis, attribution, testing, optimization cycles." }, { q: "Describe your approach to brand repositioning.", hint: "Research, strategy, messaging, execution, measurement." }, { q: "How do you align marketing with sales and product teams?", hint: "Shared KPIs, regular syncs, SLAs, tools." }, { q: "What is your framework for entering a new market?", hint: "Research, competitive analysis, localization, partnerships." }] },
    behavioral: { Fresher: [{ q: "Describe a creative campaign you developed.", hint: "STAR: Idea, execution, results, learnings." }, { q: "How do you handle tight deadlines for campaigns?", hint: "STAR: Prioritization, delegation, quality control." }, { q: "Tell me about handling negative brand feedback.", hint: "STAR: Monitoring, response strategy, resolution." }, { q: "Describe working with a cross-functional team.", hint: "STAR: Collaboration, communication, outcome." }, { q: "How have you used data to improve a marketing initiative?", hint: "STAR: Analysis, insight, action, improvement." }], "Mid-level": [{ q: "Tell me about a campaign that failed and what you learned.", hint: "STAR: Honest assessment, root cause, changes made." }, { q: "Describe leading a product launch.", hint: "STAR: Planning, execution, cross-functional, results." }, { q: "How have you handled budget cuts to your marketing programs?", hint: "STAR: Prioritization, creative solutions, impact." }, { q: "Tell me about building a marketing team.", hint: "STAR: Hiring, training, culture, results." }, { q: "Describe a time you influenced a business strategy.", hint: "STAR: Data-driven insight, presentation, outcome." }], Senior: [{ q: "Tell me about transforming a company's marketing approach.", hint: "STAR: Assessment, strategy, execution, measurable results." }, { q: "How have you managed a marketing crisis?", hint: "STAR: Rapid response, communication, resolution, prevention." }, { q: "Describe building a brand from scratch.", hint: "STAR: Research, strategy, identity, launch, growth." }, { q: "How have you driven marketing innovation?", hint: "STAR: New channels, technologies, approaches, ROI." }, { q: "Tell me about navigating competing executive priorities.", hint: "STAR: Data, communication, compromise, results." }] },
    situational: { Fresher: [{ q: "If a social media post goes viral for wrong reasons, what do you do?", hint: "Assess, respond quickly, be transparent, learn." }, { q: "How would you market a product with zero budget?", hint: "Social media, content, partnerships, community, PR." }, { q: "What would you do if campaign metrics are below target?", hint: "Analyze, identify issues, optimize, communicate." }, { q: "If asked to market a product you don't believe in, what do you do?", hint: "Find genuine benefits, focus on audience needs, be ethical." }, { q: "How would you handle conflicting feedback from stakeholders?", hint: "Listen, data-driven approach, test, iterate." }], "Mid-level": [{ q: "How would you handle a competitor launching a similar campaign?", hint: "Differentiate, accelerate, pivot if needed, double down on strengths." }, { q: "If your best-performing channel suddenly drops, what do you do?", hint: "Investigate, diversify, reallocate, test alternatives." }, { q: "How would you handle a PR crisis during a major campaign?", hint: "Pause campaign, address crisis, transparent communication." }, { q: "What if sales team says marketing leads are low quality?", hint: "Review criteria, analyze data, align on definitions, improve." }, { q: "How would you justify marketing spend to a skeptical CFO?", hint: "ROI data, attribution, industry benchmarks, testing results." }], Senior: [{ q: "How would you handle a complete brand overhaul?", hint: "Research, stakeholder alignment, phased approach, measurement." }, { q: "If asked to cut marketing budget by 50%, what goes?", hint: "ROI analysis, essential vs nice-to-have, creative alternatives." }, { q: "How would you enter a saturated market?", hint: "Differentiation, niche focus, innovative channels, partnerships." }, { q: "What if your CMO vision conflicts with data insights?", hint: "Present data clearly, propose tests, respect decision." }, { q: "How would you build marketing ops from zero?", hint: "Audit, tools selection, processes, team, measurement." }] },
    hr: { Fresher: [{ q: "Why did you choose marketing as a career?", hint: "Creativity + analytics, impact, specific inspiration." }, { q: "Where do you see yourself in 5 years?", hint: "Marketing leadership, specialization, continuous growth." }, { q: "What is your salary expectation?", hint: "Market research, range, flexibility." }, { q: "Why should we hire you?", hint: "Skills, passion, cultural fit, unique perspective." }, { q: "Any questions for us?", hint: "Culture, campaigns, growth, tools, team." }], "Mid-level": [{ q: "Why are you looking for a change?", hint: "Growth, new challenges, better alignment." }, { q: "What is your greatest marketing achievement?", hint: "STAR: Campaign, results, learnings." }, { q: "How do you handle work-life balance?", hint: "Boundaries, productivity, sustainability." }, { q: "What marketing trend excites you most?", hint: "AI, personalization, specific trend with reasoning." }, { q: "Describe your ideal role.", hint: "Responsibilities, team, culture, impact." }], Senior: [{ q: "What is your leadership philosophy?", hint: "Empowerment, mentoring, results-oriented." }, { q: "How do you handle hiring decisions?", hint: "Culture fit, skills, diversity, growth potential." }, { q: "Why this company?", hint: "Brand, challenges, alignment, specific excitement." }, { q: "What would your first 90 days look like?", hint: "Audit, relationships, quick wins, strategy." }, { q: "What legacy do you want to build?", hint: "Culture, processes, results, team development." }] },
  },
  "Sales": {
    technical: { Fresher: [{ q: "What is the sales funnel and its stages?", hint: "Awareness, Interest, Decision, Action with examples." }, { q: "How do you handle sales objections?", hint: "Listen, empathize, address, confirm, techniques." }, { q: "What is the difference between B2B and B2C sales?", hint: "Decision cycle, stakeholders, relationship, approach." }, { q: "Explain cold calling best practices.", hint: "Research, script, value proposition, follow-up." }, { q: "What CRM tools have you used?", hint: "Salesforce, HubSpot, features, pipeline management." }], "Mid-level": [{ q: "How do you build and manage a sales pipeline?", hint: "Stages, qualification, forecasting, metrics." }, { q: "Explain solution selling methodology.", hint: "Discovery, pain points, custom solutions, value." }, { q: "How do you handle long sales cycles?", hint: "Nurturing, touchpoints, stakeholder management." }, { q: "What is your approach to sales forecasting?", hint: "Methods, accuracy, data-driven, pipeline analysis." }, { q: "How do you upsell and cross-sell effectively?", hint: "Customer needs, timing, value proposition, trust." }], Senior: [{ q: "How do you build a sales strategy for a new market?", hint: "Research, segmentation, partnerships, team, metrics." }, { q: "What is your approach to enterprise sales?", hint: "Account planning, multi-stakeholder, long cycle." }, { q: "How do you structure sales compensation plans?", hint: "Base, commission, quotas, accelerators, alignment." }, { q: "Describe your channel partnership strategy.", hint: "Selection, onboarding, enablement, measurement." }, { q: "How do you align sales with product roadmap?", hint: "Customer feedback, regular syncs, shared KPIs." }] },
    behavioral: { Fresher: [{ q: "Describe your biggest sales win.", hint: "STAR: Challenge, approach, persuasion, result." }, { q: "How do you handle rejection?", hint: "STAR: Resilience, learning, persistence." }, { q: "Tell me about building rapport with a difficult client.", hint: "STAR: Patience, listening, finding common ground." }, { q: "Describe exceeding a sales target.", hint: "STAR: Strategy, effort, specific numbers." }, { q: "How have you handled a dissatisfied customer?", hint: "STAR: Listening, solution, retention." }], "Mid-level": [{ q: "Tell me about winning back a lost account.", hint: "STAR: Analysis, strategy, re-engagement, result." }, { q: "Describe managing a complex multi-stakeholder deal.", hint: "STAR: Stakeholder mapping, tailored approach, closing." }, { q: "How have you coached underperforming team members?", hint: "STAR: Diagnosis, support, improvement plan, outcome." }, { q: "Tell me about negotiating a large deal.", hint: "STAR: Preparation, tactics, win-win, outcome." }, { q: "Describe a time you had to pivot your sales strategy.", hint: "STAR: Market change, analysis, new approach, results." }], Senior: [{ q: "Tell me about building a sales team from scratch.", hint: "STAR: Hiring, training, culture, processes, results." }, { q: "Describe transforming a declining sales organization.", hint: "STAR: Assessment, strategy, execution, turnaround." }, { q: "How have you managed a major account crisis?", hint: "STAR: Quick response, executive involvement, resolution." }, { q: "Tell me about driving a significant revenue milestone.", hint: "STAR: Strategy, team alignment, execution, results." }, { q: "Describe navigating competitive pressure.", hint: "STAR: Differentiation, value selling, customer focus." }] },
    situational: { Fresher: [{ q: "If a prospect says 'your price is too high', what do you do?", hint: "Explore value, understand budget, negotiate, don't just discount." }, { q: "How would you approach a prospect who's happy with competition?", hint: "Find gaps, add value, long-term relationship, timing." }, { q: "What would you do if you're behind your monthly target?", hint: "Analyze pipeline, increase activity, prioritize, communicate." }, { q: "If a client requests a feature you don't have, how do you respond?", hint: "Acknowledge, explore workaround, feedback to product." }, { q: "How would you handle a colleague stealing your lead?", hint: "Professional conversation, clear boundaries, manager involvement." }], "Mid-level": [{ q: "How would you handle a key account threatening to leave?", hint: "Root cause, executive meeting, retention plan, value reinforcement." }, { q: "If your sales process isn't working, what do you change?", hint: "Analyze metrics, identify bottleneck, test changes, measure." }, { q: "How would you sell a product you're not familiar with?", hint: "Rapid learning, customer focus, expert support, honesty." }, { q: "What if marketing leads don't match your ideal customer?", hint: "Data sharing, alignment meeting, criteria refinement, feedback." }, { q: "How would you handle pressure to discount?", hint: "Value justification, creative alternatives, negotiate terms." }], Senior: [{ q: "How would you handle a complete restructuring of the sales team?", hint: "Assessment, vision, communication, phased execution." }, { q: "If entering a market with no brand recognition, what's your plan?", hint: "Partnerships, thought leadership, targeted outreach, PR." }, { q: "How would you handle a sales team with low morale?", hint: "Listen, address concerns, wins, incentives, culture." }, { q: "What if the CEO wants unrealistic sales targets?", hint: "Data-driven conversation, propose alternatives, plan." }, { q: "How would you handle a product recall affecting your clients?", hint: "Proactive communication, support plan, retention strategy." }] },
    hr: { Fresher: [{ q: "Why sales?", hint: "People skills, results, impact, specific motivation." }, { q: "Where do you see yourself in 5 years?", hint: "Sales leadership, key accounts, specialization." }, { q: "Salary expectations?", hint: "Research, OTE understanding, base + commission." }, { q: "Why should we hire you?", hint: "Communication, resilience, relevant experience." }, { q: "Questions for us?", hint: "Territory, quota, tools, team, growth." }], "Mid-level": [{ q: "Why are you leaving current role?", hint: "Growth, market, product alignment." }, { q: "Biggest professional achievement?", hint: "Revenue target, key deal, team building." }, { q: "How do you handle rejection and failure?", hint: "Resilience, learning, persistence, examples." }, { q: "What motivates you in sales?", hint: "Competition, helping clients, financial rewards." }, { q: "Ideal sales culture?", hint: "Collaborative, competitive, supportive, data-driven." }], Senior: [{ q: "Leadership style?", hint: "Lead by example, coaching, empowerment." }, { q: "How do you retain top performers?", hint: "Recognition, development, compensation, culture." }, { q: "Why this company?", hint: "Product, market, culture, growth potential." }, { q: "First 90 days plan?", hint: "Assess, relationships, quick wins, strategy." }, { q: "What would you change about our sales approach?", hint: "Observation-based, data-driven, respectful suggestions." }] },
  },
  "HR": {
    technical: { Fresher: [{ q: "What are the key HR functions?", hint: "Recruitment, training, compensation, compliance, relations." }, { q: "Explain the recruitment lifecycle.", hint: "Sourcing, screening, interviewing, offer, onboarding." }, { q: "What is employee engagement?", hint: "Definition, importance, measurement, improvement strategies." }, { q: "What are labor laws every HR should know?", hint: "Country-specific laws, compliance requirements." }, { q: "What HRIS tools are you familiar with?", hint: "SAP, Workday, BambooHR, features, experience." }], "Mid-level": [{ q: "How do you design a compensation structure?", hint: "Market benchmarking, internal equity, grades, benefits." }, { q: "Explain performance management best practices.", hint: "Goal setting, feedback, reviews, development plans." }, { q: "How do you handle workplace investigations?", hint: "Process, documentation, confidentiality, resolution." }, { q: "What is your approach to talent management?", hint: "Identification, development, succession, retention." }, { q: "How do you measure HR effectiveness?", hint: "KPIs, attrition, engagement, time-to-hire, cost-per-hire." }], Senior: [{ q: "How do you align HR strategy with business objectives?", hint: "Workforce planning, organizational design, culture." }, { q: "What is your approach to organizational development?", hint: "Assessment, change management, culture, structure." }, { q: "How do you build a diverse and inclusive workplace?", hint: "Strategy, metrics, training, policies, accountability." }, { q: "Describe your approach to HR technology transformation.", hint: "Assessment, selection, implementation, adoption, ROI." }, { q: "How do you manage HR during mergers and acquisitions?", hint: "Due diligence, integration, culture, communication." }] },
    behavioral: { Fresher: [{ q: "Describe resolving an employee conflict.", hint: "STAR: Listening, mediation, resolution." }, { q: "How did you handle a difficult recruitment situation?", hint: "STAR: Challenge, creative approach, result." }, { q: "Tell me about organizing a company event.", hint: "STAR: Planning, coordination, execution." }, { q: "How did you handle confidential information?", hint: "STAR: Discretion, professionalism, trust." }, { q: "Describe improving an HR process.", hint: "STAR: Problem, solution, implementation, impact." }], "Mid-level": [{ q: "Tell me about handling a termination.", hint: "STAR: Legal compliance, empathy, professionalism." }, { q: "Describe implementing a new HR policy.", hint: "STAR: Need, design, rollout, adoption." }, { q: "How did you handle a harassment complaint?", hint: "STAR: Process, investigation, resolution, prevention." }, { q: "Tell me about reducing employee turnover.", hint: "STAR: Analysis, strategies, results." }, { q: "Describe managing a layoff process.", hint: "STAR: Planning, communication, support, compliance." }], Senior: [{ q: "Tell me about transforming company culture.", hint: "STAR: Assessment, strategy, execution, measurement." }, { q: "How did you handle executive succession?", hint: "STAR: Planning, development, transition." }, { q: "Describe leading HR through a crisis.", hint: "STAR: Communication, support, adaptation." }, { q: "How have you built an employer brand?", hint: "STAR: Strategy, channels, measurement, results." }, { q: "Tell me about a failed HR initiative and lessons.", hint: "STAR: Honest assessment, root cause, improvements." }] },
    situational: { Fresher: [{ q: "If an employee comes to you with a complaint about their manager, what do you do?", hint: "Listen, document, investigate, follow process." }, { q: "How would you handle an employee asking for a raise?", hint: "Policy, market data, performance, communication." }, { q: "What if two candidates are equally qualified?", hint: "Culture fit, growth potential, diversity, references." }, { q: "How would you onboard a remote employee?", hint: "Technology, buddy system, check-ins, documentation." }, { q: "What if an employee is consistently late?", hint: "Private conversation, understand reasons, set expectations." }], "Mid-level": [{ q: "How would you handle an employee threatening legal action?", hint: "Stay calm, document, legal counsel, follow process." }, { q: "If engagement scores drop significantly, what do you do?", hint: "Root cause analysis, action planning, communication." }, { q: "How would you handle mass resignations?", hint: "Exit interviews, retention plan, workload management." }, { q: "What if a department head wants to bypass HR policies?", hint: "Policy reasoning, compliance, escalation if needed." }, { q: "How would you restructure underperforming departments?", hint: "Assessment, planning, communication, support." }], Senior: [{ q: "How would you handle a unionization attempt?", hint: "Legal compliance, employee needs, communication, rights." }, { q: "If the board wants to cut HR budget by 40%, what goes?", hint: "Prioritize compliance, outsource, automate, negotiate." }, { q: "How would you manage HR during rapid scaling?", hint: "Scalable processes, technology, culture preservation." }, { q: "What if leadership has values misalignment?", hint: "Assess impact, coach, escalate, protect culture." }, { q: "How would you build HR in a startup from scratch?", hint: "Compliance first, then culture, processes, technology." }] },
    hr: { Fresher: [{ q: "Why HR?", hint: "People impact, organizational development, specific passion." }, { q: "5-year plan?", hint: "HR leadership, specialization, CHRO aspirations." }, { q: "Salary expectations?", hint: "Market research, range, benefits consideration." }, { q: "Why us?", hint: "Company culture, HR challenges, alignment." }, { q: "Questions?", hint: "Team, challenges, culture, growth." }], "Mid-level": [{ q: "Why looking for change?", hint: "Growth, new challenges, industry change." }, { q: "Biggest HR achievement?", hint: "Policy, culture change, retention improvement." }, { q: "Handling work stress?", hint: "Self-care, boundaries, support systems." }, { q: "HR trend you're excited about?", hint: "AI, employee experience, remote work." }, { q: "Ideal work environment?", hint: "Progressive, people-first, data-driven." }], Senior: [{ q: "Leadership philosophy?", hint: "Servant leadership, empowerment, accountability." }, { q: "Building high-performing HR teams?", hint: "Hiring, development, culture, specialization." }, { q: "Why this role?", hint: "Company stage, challenges, impact potential." }, { q: "First 90 days?", hint: "Listen, audit, relationships, quick wins." }, { q: "What would you change about HR in general?", hint: "Strategic role, technology, employee experience." }] },
  },
  "Finance": {
    technical: { Fresher: [{ q: "Explain the three financial statements.", hint: "Income statement, balance sheet, cash flow, relationships." }, { q: "What is the time value of money?", hint: "Present value, future value, discounting, compounding." }, { q: "Explain the difference between GAAP and IFRS.", hint: "Standards, geographical usage, key differences." }, { q: "What is working capital?", hint: "Current assets - liabilities, importance, management." }, { q: "How do you perform a DCF analysis?", hint: "Cash flow projection, discount rate, terminal value." }], "Mid-level": [{ q: "How do you assess a company's financial health?", hint: "Ratio analysis, trend analysis, industry comparison." }, { q: "Explain financial modeling best practices.", hint: "Structure, assumptions, sensitivity, documentation." }, { q: "What is your approach to budgeting and forecasting?", hint: "Methods, variance analysis, rolling forecasts." }, { q: "How do you evaluate investment opportunities?", hint: "NPV, IRR, payback period, risk assessment." }, { q: "Explain transfer pricing concepts.", hint: "Methods, compliance, documentation, arm's length." }], Senior: [{ q: "How do you build a financial strategy for growth?", hint: "Capital allocation, M&A, financing, risk management." }, { q: "What is your approach to treasury management?", hint: "Cash management, FX risk, investments, banking." }, { q: "How do you manage financial risk?", hint: "Identification, assessment, mitigation, monitoring." }, { q: "Describe your approach to investor relations.", hint: "Communication, reporting, transparency, relationship." }, { q: "How do you drive financial transformation?", hint: "Technology, processes, team, automation, analytics." }] },
    behavioral: { Fresher: [{ q: "Describe a financial analysis you're proud of.", hint: "STAR: Problem, methodology, insight, impact." }, { q: "How do you ensure accuracy in your work?", hint: "STAR: Double-checking, peer review, reconciliation." }, { q: "Tell me about handling a tight deadline for a report.", hint: "STAR: Prioritization, efficiency, quality." }, { q: "Describe working with non-finance stakeholders.", hint: "STAR: Communication, simplification, collaboration." }, { q: "How did you handle a calculation error?", hint: "STAR: Discovery, correction, prevention." }], "Mid-level": [{ q: "Tell me about presenting bad financial news.", hint: "STAR: Preparation, clarity, solutions, outcome." }, { q: "Describe improving a financial process.", hint: "STAR: Identification, redesign, implementation, savings." }, { q: "How did you handle a complex audit?", hint: "STAR: Preparation, cooperation, resolution." }, { q: "Tell me about a strategic financial recommendation.", hint: "STAR: Analysis, presentation, decision, impact." }, { q: "Describe managing financial compliance.", hint: "STAR: Requirements, implementation, monitoring." }], Senior: [{ q: "Tell me about a major financial decision you influenced.", hint: "STAR: Analysis, stakeholders, decision, outcome." }, { q: "Describe building a finance team.", hint: "STAR: Hiring, development, culture, results." }, { q: "How did you handle a financial crisis?", hint: "STAR: Assessment, action plan, communication, resolution." }, { q: "Tell me about a successful M&A transaction.", hint: "STAR: Due diligence, valuation, negotiation, integration." }, { q: "Describe driving digital transformation in finance.", hint: "STAR: Vision, tools, change management, ROI." }] },
    situational: { Fresher: [{ q: "If you find a discrepancy in financial records, what do you do?", hint: "Investigate, trace, correct, report, prevent." }, { q: "How would you handle pressure to manipulate numbers?", hint: "Ethics, refusal, documentation, escalation." }, { q: "What if your financial model gives unexpected results?", hint: "Verify inputs, check formulas, sensitivity analysis." }, { q: "How would you explain financial concepts to non-finance teams?", hint: "Analogies, visuals, simplification, patience." }, { q: "What if you disagree with an accounting treatment?", hint: "Research, consult, document reasoning, escalate." }], "Mid-level": [{ q: "How would you handle a major budget overrun?", hint: "Root cause, corrective action, communication, prevention." }, { q: "If asked to cut costs by 20%, where do you start?", hint: "Analysis, prioritization, strategic cuts, stakeholder input." }, { q: "How would you handle a regulatory inquiry?", hint: "Legal counsel, documentation, cooperation, transparency." }, { q: "What if your forecast is significantly off?", hint: "Analyze variance, communicate, improve methodology." }, { q: "How would you handle competing investment proposals?", hint: "Consistent evaluation criteria, NPV, strategic alignment." }], Senior: [{ q: "How would you handle a liquidity crisis?", hint: "Cash management, credit facilities, asset optimization." }, { q: "If facing hostile takeover, what financial defenses?", hint: "Poison pill, white knight, crown jewels, shareholder value." }, { q: "How would you restructure a troubled division?", hint: "Assessment, options, stakeholder management, execution." }, { q: "What if the board wants aggressive revenue recognition?", hint: "Ethics, compliance, risk explanation, alternatives." }, { q: "How would you build a finance function in a new market?", hint: "Compliance, local expertise, systems, processes." }] },
    hr: { Fresher: [{ q: "Why finance?", hint: "Analytical mind, business impact, career path." }, { q: "5-year goal?", hint: "CPA/CFA, senior roles, specialization." }, { q: "Salary expectations?", hint: "Market research, range." }, { q: "Why us?", hint: "Company, industry, growth." }, { q: "Questions?", hint: "Team, growth, tools, culture." }], "Mid-level": [{ q: "Why the change?", hint: "Growth, new industry, better role." }, { q: "Greatest achievement?", hint: "Financial impact, process improvement." }, { q: "Work under pressure?", hint: "Month-end, audits, prioritization." }, { q: "Professional development?", hint: "CPA, courses, conferences." }, { q: "Ideal role?", hint: "Responsibilities, team, impact." }], Senior: [{ q: "Leadership style?", hint: "Strategic, collaborative, results-driven." }, { q: "Building finance excellence?", hint: "Talent, processes, technology." }, { q: "Why this company?", hint: "Stage, challenges, opportunity." }, { q: "First 90 days?", hint: "Assess, relationships, strategy." }, { q: "Vision for finance?", hint: "Strategic partner, technology, talent." }] },
  },
  "Product Manager": {
    technical: { Fresher: [{ q: "What is a product roadmap?", hint: "Definition, components, prioritization, communication." }, { q: "Explain the product lifecycle.", hint: "Introduction, growth, maturity, decline stages." }, { q: "What is an MVP?", hint: "Minimum Viable Product, purpose, examples." }, { q: "How do you prioritize features?", hint: "MoSCoW, RICE, value vs effort, stakeholder input." }, { q: "What metrics would you track for a new product?", hint: "DAU, retention, NPS, conversion, revenue." }], "Mid-level": [{ q: "How do you define and validate product-market fit?", hint: "User research, metrics, iteration, Sean Ellis test." }, { q: "Explain your approach to product discovery.", hint: "User interviews, prototyping, testing, data analysis." }, { q: "How do you balance technical debt with new features?", hint: "Assessment, prioritization, communication, allocation." }, { q: "What is your framework for making go/no-go decisions?", hint: "Data, user feedback, market, resources, risk." }, { q: "How do you write effective product specifications?", hint: "User stories, acceptance criteria, wireframes, edge cases." }], Senior: [{ q: "How do you build a product strategy?", hint: "Vision, market analysis, competitive positioning, roadmap." }, { q: "What is your approach to platform vs feature decisions?", hint: "Long-term value, scalability, ecosystem, data." }, { q: "How do you manage a product portfolio?", hint: "Resource allocation, synergies, lifecycle management." }, { q: "Describe your pricing strategy framework.", hint: "Value-based, competitive, segmentation, testing." }, { q: "How do you measure product-led growth?", hint: "Activation, retention, expansion, viral loops." }] },
    behavioral: { Fresher: [{ q: "Describe a product you love and how you'd improve it.", hint: "Analysis, user empathy, specific improvements." }, { q: "How did you handle conflicting stakeholder priorities?", hint: "STAR: Data, communication, compromise." }, { q: "Tell me about a time you used data to make a decision.", hint: "STAR: Data analysis, insight, action, result." }, { q: "Describe working with engineers effectively.", hint: "STAR: Communication, respect, collaboration." }, { q: "How did you handle a feature request you disagreed with?", hint: "STAR: Listening, data, alternative, outcome." }], "Mid-level": [{ q: "Tell me about launching a successful product feature.", hint: "STAR: Discovery, development, launch, metrics." }, { q: "Describe a pivot decision you made.", hint: "STAR: Signals, analysis, decision, outcome." }, { q: "How did you handle a product failure?", hint: "STAR: Learning, iteration, resilience." }, { q: "Tell me about influencing without authority.", hint: "STAR: Stakeholder management, persuasion, results." }, { q: "Describe building cross-functional alignment.", hint: "STAR: Communication, shared goals, process." }], Senior: [{ q: "Tell me about defining a product vision.", hint: "STAR: Market insight, vision, alignment, execution." }, { q: "Describe scaling a product team.", hint: "STAR: Structure, hiring, processes, culture." }, { q: "How did you drive a major product transformation?", hint: "STAR: Assessment, strategy, execution, results." }, { q: "Tell me about killing a product or feature.", hint: "STAR: Data, decision, communication, migration." }, { q: "Describe building a product culture.", hint: "STAR: Values, practices, tools, outcomes." }] },
    situational: { Fresher: [{ q: "If engineers say a feature will take 3x longer than expected, what do you do?", hint: "Understand, scope, alternatives, communicate." }, { q: "How would you handle a feature users hate?", hint: "Data, user research, iterate or remove." }, { q: "What if your roadmap needs to change due to market shift?", hint: "Assess impact, reprioritize, communicate, adapt." }, { q: "If design and engineering disagree, how do you mediate?", hint: "User focus, data, compromise, prototype." }, { q: "How would you handle a competitor copying your key feature?", hint: "Differentiate, accelerate, innovate." }], "Mid-level": [{ q: "How would you handle a CEO request that conflicts with user data?", hint: "Present data, understand reasoning, propose test." }, { q: "If your product has low adoption, what do you investigate?", hint: "Onboarding, value prop, usability, market fit." }, { q: "How would you handle tech debt making features impossible?", hint: "Quantify impact, phased approach, stakeholder buy-in." }, { q: "What if sales wants features that hurt product vision?", hint: "Understand need, find alternatives, protect vision." }, { q: "How would you validate a risky product bet?", hint: "Prototype, small test, metrics, iterate." }], Senior: [{ q: "How would you rebuild product culture after layoffs?", hint: "Communication, vision, empowerment, stability." }, { q: "If entering a market dominated by a major player, what's your strategy?", hint: "Niche focus, differentiation, agility advantage." }, { q: "How would you handle product-level technical debt crisis?", hint: "Assessment, prioritization, phased plan, investment case." }, { q: "What if board wants to pivot the entire product?", hint: "Data analysis, options, risk assessment, execution plan." }, { q: "How would you manage a product with conflicting global market needs?", hint: "Platform approach, localization, prioritization." }] },
    hr: { Fresher: [{ q: "Why product management?", hint: "Intersection of business, tech, design, impact." }, { q: "5-year vision?", hint: "Senior PM, product leadership, founder." }, { q: "Salary expectations?", hint: "Market research, range, equity consideration." }, { q: "Why us?", hint: "Product, market, culture, challenge." }, { q: "Questions?", hint: "Product vision, team, methodology, growth." }], "Mid-level": [{ q: "Why leaving current role?", hint: "Growth, product type, market, impact." }, { q: "Proudest product achievement?", hint: "Metrics, user impact, innovation." }, { q: "Work-life balance?", hint: "Sustainable pace, prioritization, boundaries." }, { q: "PM methodology preference?", hint: "Agile, lean, data-driven, situational." }, { q: "Ideal team structure?", hint: "Squad model, cross-functional, autonomous." }], Senior: [{ q: "PM leadership philosophy?", hint: "Empowerment, user focus, data-driven." }, { q: "Building product teams?", hint: "Hiring, culture, processes, autonomy." }, { q: "Why this company specifically?", hint: "Product challenge, market, vision alignment." }, { q: "First 90 days?", hint: "Learn, listen, assess, quick wins." }, { q: "Product vision for our company?", hint: "Research-based, ambitious, actionable." }] },
  },
  "Designer": {
    technical: { Fresher: [{ q: "What is the difference between UX and UI design?", hint: "Experience vs interface, research vs visuals, examples." }, { q: "Explain the design thinking process.", hint: "Empathize, Define, Ideate, Prototype, Test." }, { q: "What tools do you use for design?", hint: "Figma, Sketch, Adobe, prototyping tools." }, { q: "What are the principles of good visual hierarchy?", hint: "Size, color, contrast, spacing, typography, alignment." }, { q: "How do you approach responsive design?", hint: "Mobile-first, breakpoints, flexible grids, testing." }], "Mid-level": [{ q: "How do you conduct user research?", hint: "Methods, interviews, surveys, usability testing, synthesis." }, { q: "Explain your design system approach.", hint: "Components, tokens, documentation, maintenance." }, { q: "How do you measure design success?", hint: "Usability metrics, task completion, satisfaction, A/B testing." }, { q: "What is your approach to accessibility?", hint: "WCAG, inclusive design, testing, implementation." }, { q: "How do you handle design handoff to developers?", hint: "Specs, components, tokens, communication, QA." }], Senior: [{ q: "How do you build a design strategy?", hint: "Research, vision, principles, execution, measurement." }, { q: "What is your approach to design operations?", hint: "Processes, tools, standards, efficiency, quality." }, { q: "How do you scale design across products?", hint: "Design system, team structure, governance." }, { q: "Describe your approach to design leadership.", hint: "Vision, hiring, mentoring, advocacy, influence." }, { q: "How do you balance innovation with consistency?", hint: "Design system flexibility, experimentation, guidelines." }] },
    behavioral: { Fresher: [{ q: "Walk me through your favorite project in your portfolio.", hint: "Process, challenges, decisions, outcome." }, { q: "How do you handle design feedback?", hint: "STAR: Openness, iteration, improvement." }, { q: "Tell me about a design you iterated on significantly.", hint: "STAR: Research, versions, testing, improvement." }, { q: "Describe collaborating with a developer.", hint: "STAR: Communication, compromise, result." }, { q: "How did you solve a complex UX problem?", hint: "STAR: Research, ideation, testing, solution." }], "Mid-level": [{ q: "Tell me about a design that impacted business metrics.", hint: "STAR: Research, design, A/B test, measurable result." }, { q: "Describe building a design system.", hint: "STAR: Planning, components, adoption, maintenance." }, { q: "How did you advocate for users against business pressure?", hint: "STAR: Data, persuasion, compromise, outcome." }, { q: "Tell me about mentoring a junior designer.", hint: "STAR: Approach, guidance, growth, impact." }, { q: "Describe a project where you had to pivot.", hint: "STAR: New data, flexibility, outcome." }], Senior: [{ q: "Tell me about elevating design maturity in an organization.", hint: "STAR: Assessment, strategy, execution, cultural change." }, { q: "Describe building and leading a design team.", hint: "STAR: Hiring, culture, processes, outcomes." }, { q: "How did you influence product strategy through design?", hint: "STAR: Research insights, strategic recommendations, impact." }, { q: "Tell me about a design failure and lessons learned.", hint: "STAR: Honest reflection, root cause, improvements." }, { q: "Describe driving design innovation.", hint: "STAR: Exploration, validation, implementation, results." }] },
    situational: { Fresher: [{ q: "If a stakeholder insists on a design you think is wrong, what do you do?", hint: "Listen, understand reasoning, present alternatives with data." }, { q: "How would you design for a user group you don't belong to?", hint: "Research, empathy, testing, inclusivity." }, { q: "What if you get conflicting feedback from different stakeholders?", hint: "Prioritize, user-centered, facilitate discussion." }, { q: "How would you approach a redesign with minimal user data?", hint: "Competitive analysis, heuristics, prototype and test." }, { q: "If a developer says your design is not feasible, what do you do?", hint: "Understand constraints, collaborate, find alternatives." }], "Mid-level": [{ q: "How would you handle a project with no design resources besides you?", hint: "Prioritize, templatize, communicate trade-offs." }, { q: "If usability testing shows users hate your design, what next?", hint: "Analyze why, identify issues, iterate, retest." }, { q: "How would you introduce design thinking to a non-design team?", hint: "Workshop, quick wins, demonstrate value, educate." }, { q: "What if product wants to skip user testing due to timeline?", hint: "Explain risk, propose quick testing, negotiate." }, { q: "How would you handle a design system that teams ignore?", hint: "Understand why, improve, educate, demonstrate value." }], Senior: [{ q: "How would you rebuild trust in design after a failed product?", hint: "Post-mortem, process improvement, small wins, transparency." }, { q: "If asked to reduce design team by half, how do you decide?", hint: "Core capabilities, cross-training, outsourcing, priorities." }, { q: "How would you unify design across acquired companies?", hint: "Audit, shared principles, phased alignment, respect." }, { q: "What if CEO wants to copy a competitor's design?", hint: "Differentiation, user needs, legal risk, alternatives." }, { q: "How would you build design culture in an engineering-driven org?", hint: "Demonstrate value, allies, education, quick wins." }] },
    hr: { Fresher: [{ q: "Why design?", hint: "Creativity, empathy, problem-solving, impact." }, { q: "5-year vision?", hint: "Senior designer, design lead, specialization." }, { q: "Salary expectations?", hint: "Market research, portfolio quality, range." }, { q: "Why us?", hint: "Product, design culture, growth." }, { q: "Questions?", hint: "Design process, tools, team, growth." }], "Mid-level": [{ q: "Why looking for change?", hint: "Design maturity, challenges, growth." }, { q: "Design achievement?", hint: "Impact, innovation, recognition." }, { q: "Creative block handling?", hint: "Techniques, inspiration, collaboration." }, { q: "Design trend excitement?", hint: "AI in design, accessibility, systems." }, { q: "Ideal design culture?", hint: "Research-driven, collaborative, innovative." }], Senior: [{ q: "Design leadership philosophy?", hint: "Empowerment, craft, impact, culture." }, { q: "Building design excellence?", hint: "Hiring, processes, standards, advocacy." }, { q: "Why this company?", hint: "Design challenge, product, impact." }, { q: "First 90 days?", hint: "Audit, relationships, vision, quick wins." }, { q: "Design industry future?", hint: "AI, ethical design, accessibility, systems." }] },
  },
};

export default function AiInterviewQuestions() {
  const [role, setRole] = useState<Role>("Software Engineer");
  const [level, setLevel] = useState<Level>("Fresher");
  const [questions, setQuestions] = useState<{ category: string; items: Question[] }[]>([]);
  const [copied, setCopied] = useState(false);
  const [expandedIdx, setExpandedIdx] = useState<string | null>(null);

  const generate = () => {
    const data = questionBank[role];
    setQuestions([
      { category: "Technical Questions", items: data.technical[level] },
      { category: "Behavioral Questions", items: data.behavioral[level] },
      { category: "Situational Questions", items: data.situational[level] },
      { category: "HR / General Questions", items: data.hr[level] },
    ]);
    setExpandedIdx(null);
  };

  const copy = () => {
    const text = questions.map((cat) =>
      `## ${cat.category}\n${cat.items.map((q, i) => `${i + 1}. ${q.q}\n   Hint: ${q.hint}`).join("\n")}`
    ).join("\n\n");
    navigator.clipboard?.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="space-y-6">
      <div>
        <label className="text-sm font-semibold text-gray-700 block mb-2">Role Type</label>
        <select className="calc-input" value={role} onChange={(e) => setRole(e.target.value as Role)}>
          {roles.map((r) => <option key={r} value={r}>{r}</option>)}
        </select>
      </div>
      <div>
        <label className="text-sm font-semibold text-gray-700 block mb-2">Experience Level</label>
        <div className="flex gap-2 flex-wrap">
          {levels.map((l) => (
            <button key={l} onClick={() => setLevel(l)} className={l === level ? "btn-primary" : "btn-secondary"}>{l}</button>
          ))}
        </div>
      </div>
      <button onClick={generate} className="btn-primary">Generate Interview Questions</button>
      {questions.length > 0 && (
        <div className="result-card space-y-6">
          <div className="flex justify-between items-center">
            <span className="text-sm font-bold text-gray-600">{role} — {level} Level (20 Questions)</span>
            <button onClick={copy} className="text-xs text-indigo-600 font-medium hover:underline">{copied ? "Copied!" : "Copy All"}</button>
          </div>
          {questions.map((cat, ci) => (
            <div key={ci}>
              <h3 className="font-bold text-gray-800 mb-3 text-base">{cat.category}</h3>
              <div className="space-y-2">
                {cat.items.map((q, qi) => {
                  const key = `${ci}-${qi}`;
                  return (
                    <div key={qi} className="bg-white rounded-xl border border-gray-100 overflow-hidden">
                      <button className="w-full text-left p-3 flex justify-between items-start gap-2 hover:bg-gray-50" onClick={() => setExpandedIdx(expandedIdx === key ? null : key)}>
                        <span className="text-gray-800"><span className="text-indigo-600 font-bold mr-2">{ci * 5 + qi + 1}.</span>{q.q}</span>
                        <span className="text-gray-400 text-xs shrink-0">{expandedIdx === key ? "Hide" : "Show"} hint</span>
                      </button>
                      {expandedIdx === key && (
                        <div className="px-3 pb-3 pt-0">
                          <div className="bg-indigo-50 rounded-lg p-3">
                            <p className="text-xs font-semibold text-indigo-600 mb-1">Answer Framework (STAR Method)</p>
                            <p className="text-sm text-indigo-800">{q.hint}</p>
                          </div>
                        </div>
                      )}
                    </div>
                  );
                })}
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
