"use client";
import { useState } from "react";

type Style = "Cheesy" | "Smooth" | "Nerdy" | "Funny" | "Romantic" | "Bollywood";

const lines: Record<Style, string[]> = {
  Cheesy: [
    "Are you a magician? Because whenever I look at you, everyone else disappears.",
    "Do you have a map? Because I just got lost in your eyes.",
    "Is your name Google? Because you have everything I've been searching for.",
    "Are you a parking ticket? Because you've got 'fine' written all over you.",
    "Do you have a Band-Aid? Because I just scraped my knee falling for you.",
    "Are you a campfire? Because you're hot and I want s'more.",
    "Is your dad a boxer? Because you're a total knockout!",
    "Are you a bank loan? Because you've got my interest.",
    "Do you believe in love at first sight, or should I walk by again?",
    "If you were a vegetable, you'd be a cute-cumber.",
    "Are you a time traveler? Because I can see you in my future.",
    "Is there an airport nearby, or is that just my heart taking off?",
    "Do you have a sunburn, or are you always this hot?",
    "Are you a wifi signal? Because I'm feeling a connection.",
    "If beauty were time, you'd be an eternity.",
    "Are you a cat? Because you're purr-fect.",
    "Is your name Chapstick? Because you're da balm.",
    "Do you have a mirror in your pocket? Because I can see myself in your pants... wait, I mean future!",
    "Are you a light switch? Because you turn me on.",
    "If you were words on a page, you'd be fine print.",
    "Are you a camera? Because every time I look at you, I smile.",
    "Is your name Ariel? Because I think we mermaid for each other.",
    "Are you a dictionary? Because you add meaning to my life.",
    "Do you have a compass? Because I'd be lost without you.",
    "Are you made of copper and tellurium? Because you're Cu-Te.",
    "Is your dad an artist? Because you're a masterpiece.",
    "Are you a snowstorm? Because you make my heart race.",
    "Do you have a name, or can I call you mine?",
    "Are you a charger? Because I'd die without you.",
    "If kisses were snowflakes, I'd send you a blizzard.",
    "Are you a donut? Because you're sweet with a great hole lot of personality.",
    "Is it hot in here, or is it just you?",
    "You must be a ninja, because you snuck into my heart.",
    "Are you a keyboard? Because you're just my type.",
    "If looks could kill, you'd be a weapon of mass destruction.",
    "Are you a bee? Because you're un-bee-lievably beautiful.",
    "Do you have a quarter? I want to call my mom and tell her I met the one.",
    "Are you a volcano? Because I lava you.",
    "If you were a fruit, you'd be a fineapple.",
    "Are you from Tennessee? Because you're the only ten I see.",
    "Is your dad a baker? Because you've got some nice buns.",
    "Are you a shooting star? Because my wish came true.",
    "Do you have a library card? Because I'm checking you out.",
    "Are you a candle? Because you light up my world.",
    "If I were a stoplight, I'd turn red every time you passed by.",
    "Are you an alien? Because you just abducted my heart.",
    "Is your name Bluetooth? Because I feel a connection.",
    "You must be a broom, because you just swept me off my feet.",
    "Are you a traffic ticket? Because you've got fine written all over you.",
    "If beauty were a crime, you'd be serving a life sentence.",
    "Are you oxygen? Because I can't live without you.",
    "Do you play soccer? Because you're a keeper.",
  ],
  Smooth: [
    "I'm not a photographer, but I can definitely picture us together.",
    "I must be a snowflake, because I've fallen for you.",
    "Something's wrong with my eyes. I can't take them off you.",
    "I was going to say something really sweet about you, but when I saw you, I became speechless.",
    "I don't believe in love at first sight, but I'm willing to make an exception for you.",
    "Excuse me, but I think you dropped something - my jaw.",
    "I'd say God bless you, but it looks like he already did.",
    "You're so beautiful, you made me forget my pickup line.",
    "I'm not drunk, I'm just intoxicated by you.",
    "Your hand looks heavy. Let me hold it for you.",
    "I seem to have lost my phone number. Can I have yours?",
    "There must be something wrong with my eyes. I can't take them off you.",
    "Aside from being sexy, what do you do for a living?",
    "You know what you'd look really beautiful in? My arms.",
    "I wasn't planning on coming out tonight, but then I heard you'd be here.",
    "If I had a star for every time you brightened my day, I'd have a galaxy.",
    "People call me [name], but you can call me tonight.",
    "I'm writing a book about the finer things in life, and I'd love to include you.",
    "I hope you know CPR, because you just took my breath away.",
    "On a scale of 1 to 10, you're a 9, and I'm the 1 you need.",
    "I've been looking for you everywhere. Oh wait, I was looking for my soulmate.",
    "You're the reason men fall in love.",
    "I was wondering if you had an extra heart. Mine was just stolen.",
    "Life without you is like a broken pencil - pointless.",
    "I'm not a genie, but I can make your dreams come true.",
    "Is there a rainbow today? I just found the treasure I've been searching for.",
    "Somebody better call God, because heaven is missing an angel.",
    "The only thing your eyes haven't told me is your name.",
    "I'd love to take you to the movies, but they don't let you bring in your own snacks.",
    "Are you a loan from a bank? Because you've got my interest.",
    "I was blinded by your beauty... I'm going to need your name and number for insurance purposes.",
    "You're like a fine wine. The more I stare, the better you look.",
    "I'm glad I brought my library card, because I'm checking you out.",
    "I don't need Twitter, I'm already following you.",
    "If beauty were a song, you'd be a symphony.",
    "I thought happiness started with an H, but mine starts with U.",
    "Do you work at Starbucks? Because I like you a latte.",
    "I must be dancing with the devil, because you're hot as hell.",
    "Are you a campfire? Because you're making me hot and bothered.",
    "You don't need keys to drive me crazy.",
    "The sparkle in your eyes is so bright, the sun must be jealous.",
    "Are you a magician? Every time I look at you, everything else disappears.",
    "You're proof that God has a sense of humor, because you're too good to be true.",
    "Let me tie your shoes, because I don't want you falling for anyone else.",
    "You know, I was going to give you a cheesy pickup line, but you're too sophisticated for that.",
    "I'd like to take you to the movies, but they don't allow snacks that fine.",
    "Your smile is my favorite notification.",
    "I've heard it said that kissing is a language of love. Would you care to have a conversation?",
    "I just moved to this city. Could you give me directions to your heart?",
    "You're like a candy bar: half sweet and half nuts.",
    "I think the gap between my fingers was meant for yours.",
  ],
  Nerdy: [
    "Are you made of copper and tellurium? Because you're Cu-Te.",
    "You must be the square root of -1, because you can't be real.",
    "Are you a carbon sample? Because I want to date you.",
    "If I were an enzyme, I'd be DNA helicase so I could unzip your genes.",
    "You're like a dictionary - you add meaning to my life.",
    "Are you a 90-degree angle? Because you're looking right!",
    "I wish I was your derivative so I could lie tangent to your curves.",
    "You must be a star, because you've got stellar personality.",
    "If you were a programming language, you'd be Python - beautiful and easy to love.",
    "Are you a 45-degree angle? Because you're acute-y.",
    "I must be a neuron, because you've got all my impulses firing.",
    "Are you the speed of light? Because time stops when I look at you.",
    "You're hotter than the bottom of my laptop after watching Netflix for 12 hours.",
    "If you were an element, you'd be Francium - the most attractive one.",
    "I'd like to calculate the slope of your curves.",
    "You must be a magnet, because I'm attracted to you.",
    "Are you a black hole? Because you're pulling me in.",
    "My love for you is like pi - irrational and never-ending.",
    "If I were a function, you'd be my asymptote - I always tend toward you.",
    "Are you WiFi? Because I'm feeling a connection.",
    "You must be made of Fluorine, Iodine, and Neon, because you're F-I-Ne.",
    "Are you a computer keyboard? Because you're just my type.",
    "I'd like to be your integral so I can be the area under your curves.",
    "You're like a quantum particle - you're always on my mind, even when I can't observe you.",
    "Are you a supercomputer? Because you're processing my feelings at incredible speed.",
    "If our love were a math problem, it would have no solution - it's infinite.",
    "You must be mitochondria, because you're the powerhouse of my heart.",
    "Are you the internet? Because I feel a strong connection.",
    "My love for you is like a concave function - always increasing.",
    "You're the CSS to my HTML - you make everything beautiful.",
    "If you were a triangle, you'd be acute one.",
    "Are you a particle accelerator? Because you make my heart race at the speed of light.",
    "I'm no mathematician, but I'm pretty good with numbers. How about giving me yours?",
    "You must be a photon, because you light up my world.",
    "If I were a Schr\u00f6dinger's cat, I'd be alive and dead - alive with you, dead without you.",
    "Are you an algorithm? Because I can't figure you out, but I can't stop trying.",
    "You're like a rare element - one of a kind and extremely valuable.",
    "I'd tell you a chemistry joke, but I know I wouldn't get a reaction... unless it's from you.",
    "Are you a thesis? Because I can't stop thinking about you.",
    "My feelings for you are like software updates - they never stop.",
    "You're the semicolon to my code - I'd break without you.",
    "If beauty were measured in bytes, you'd be a yottabyte.",
    "Are you a firewall? Because you've blocked everyone else from my heart.",
    "You must be a singularity, because everything revolves around you.",
    "My heart beats for you at 120 BPM - way above resting rate.",
    "Are you a star? Because your beauty collapses my rational thought into a singularity.",
    "I don't need Google - you're everything I've been searching for.",
    "You're like a perfectly optimized algorithm - efficient and impressive.",
    "If life were a video game, you'd be the ultimate achievement.",
    "Are you a database? Because I want to establish a connection with you.",
    "You must be React, because you've got me hooked.",
  ],
  Funny: [
    "Are you a bank loan? Because you've got my interest... and my anxiety.",
    "I'm not a hoarder, but I really want to keep you forever.",
    "Are you my appendix? Because I have a funny feeling in my stomach that makes me want to take you out.",
    "I'd give up my WiFi password for you, and I don't do that for just anyone.",
    "Are you a meme? Because I'd like to share you with all my friends... wait, no, I want to keep you to myself.",
    "If you were a burger at McDonald's, you'd be the McGorgeous.",
    "I'm not a photographer, but I can picture us together... awkwardly.",
    "Are you a haunted house? Because I'm going to scream if you don't go out with me.",
    "I'd offer you my jacket, but I'm already cold. But I'd still offer it anyway because I'm a gentleman.",
    "Is your name Dunkin? Because I Donut want to live without you.",
    "I'm not sure what's more beautiful - the sunset or you. Just kidding, it's definitely the sunset. No wait, it's you!",
    "Do you have GPS? Because I keep getting lost in your eyes... and also because I have a terrible sense of direction.",
    "I must be a broom, because I'm swept off my feet. Wait, that's supposed to be you. Let me start over.",
    "Are you a cat? Because I'm feline a connection between us.",
    "I'd share my food with you, and I NEVER share my food.",
    "Are you a washing machine? Because I want to put my dirty... laundry in you. LAUNDRY. I said laundry.",
    "If you were a pizza, you'd be the supreme... no, the EXTRA supreme.",
    "My mom said I should follow my dreams. So here I am, following you.",
    "Are you Netflix? Because I could binge-watch you all day.",
    "I'd like to take you on a date, but I just checked my bank account, so... coffee?",
    "You're so sweet, you could put Cadbury out of business.",
    "Are you a snooze button? Because I want to hit you over and over again every morning... wait, that came out wrong.",
    "I was going to tell you a joke, but your beauty already has me laughing nervously.",
    "If you were a potato, you'd be a sweet one.",
    "I'm not a weatherman, but you can expect a few inches tonight... of snow. I was talking about snow.",
    "Are you an elevator? Because I want to go down... to the lobby with you for dinner.",
    "I'd swim across the ocean for you. Just kidding, I can barely swim. But I'd take a flight!",
    "You're like my phone battery - I can't let you die on me.",
    "Are you a keyboard? Because you're totally my type... get it? Type?",
    "I was wondering if you're an alien, because you've just abducted my heart. And possibly my dignity.",
    "If our love story were a movie, it'd be a comedy because of all my awkward moments around you.",
    "You're so hot, you make a jalapeño look like a popsicle.",
    "I tried to come up with a pickup line, but my brain stopped working when I saw you.",
    "Are you a parking space? Because dang, you're tight... I mean hard to find. HARD TO FIND.",
    "I'd like to invite you to dinner, but I burned the last three things I cooked. So... restaurant?",
    "You're proof that evolution works in mysterious ways. Very attractive, mysterious ways.",
    "I'm no electrician, but I can light up your... Christmas tree. Your Christmas tree.",
    "Are you a dictionary? Because you give me more definitions of beauty than I knew existed.",
    "I'd climb every mountain for you. Just kidding, have you SEEN those mountains? But I'd hike a small hill!",
    "If I had a dollar for every time you crossed my mind, I'd have enough for dinner. Want to join?",
    "You're like a library book - I want to check you out and never return you.",
    "Are you a magician? Because every time I look at you, everyone else disappears. Or maybe I just need glasses.",
    "I was told I should follow my dreams, so I'm just going to stand here and stare at you.",
    "If you were a food, you'd be an everything bagel - because you've got everything.",
    "I'm not a genie, but I can grant three wishes. Wait, no I can't. But I CAN buy you coffee.",
    "You're hotter than my laptop when I have 47 browser tabs open.",
    "Are you ice cream? Because I scream every time I see you. That sounded less creepy in my head.",
    "I tried to write you a poem, but 'roses are red, violets are blue, I like your face' was the best I could do.",
    "If beauty were illegal, you'd be on death row. Too dark? Sorry, let me try again.",
    "You're like homework - I should be doing you. Wait, that's not right either.",
    "I must be a light switch, because you turn me... into a better person. A BETTER PERSON.",
  ],
  Romantic: [
    "I've been thinking about you, and I realized - you're the answer to every wish I never knew I made.",
    "If I had to choose between breathing and loving you, I'd use my last breath to say I love you.",
    "They say nothing lasts forever. Would you be my nothing?",
    "Every love song makes sense when I'm looking at you.",
    "I don't know what I did to deserve crossing paths with you, but I'm grateful every single day.",
    "Your smile is the only sunrise I need.",
    "I've always been a dreamer, but you're better than anything I could have imagined.",
    "If I could rearrange the alphabet, I'd put U and I together.",
    "You're the kind of beautiful that takes my breath away and gives me life at the same time.",
    "I didn't believe in miracles until I saw you.",
    "If my heart were a compass, it would always point to you.",
    "You are the poem I never knew how to write and the song I never knew how to sing.",
    "The world stops spinning every time you smile.",
    "I was lost before I found you. Now I'm home.",
    "You don't just cross my mind - you live in it.",
    "If love were a ocean, you'd be my entire sea.",
    "I'd cross a thousand miles just to see you smile once.",
    "Your eyes are like the stars - I could get lost in them forever.",
    "Before you, I was just existing. With you, I'm living.",
    "You are the missing piece I didn't know my heart was looking for.",
    "If I could give you one thing, it would be the ability to see yourself through my eyes.",
    "Every moment with you feels like a beautiful dream I never want to wake up from.",
    "You're not just someone I love - you're someone I choose, every single day.",
    "The way you look at me makes me believe I could do anything.",
    "I fall in love with you a little more every day, and I didn't think that was possible.",
    "You are my favorite chapter in the story of my life.",
    "If love had a face, it would look exactly like yours.",
    "I've seen a lot of beautiful things in my life, but nothing compares to you.",
    "You make ordinary moments feel extraordinary.",
    "My heart whispers your name with every beat.",
    "If I could hold time still, I'd freeze every moment with you.",
    "You're the calm in my chaos and the light in my darkness.",
    "I never knew what love was until you showed me.",
    "Your love is the sweetest gift I've ever received.",
    "In a world full of temporary, you are my forever.",
    "They say home is where the heart is. My heart is wherever you are.",
    "I would choose you in a hundred lifetimes.",
    "If my love for you were a star, it would outshine the entire galaxy.",
    "You complete every sentence my heart tries to speak.",
    "Falling for you wasn't falling at all - it was flying.",
    "I could search the entire world and never find another you.",
    "Every time I see you, I fall in love all over again.",
    "You are the reason I believe in love.",
    "If love were a journey, you'd be my favorite destination.",
    "Your love feels like coming home after the longest day.",
    "I want to be your last everything.",
    "You are the dream I refused to wake up from.",
    "I found forever when I found you.",
    "The best part of my day is any part that includes you.",
    "If the world ended tomorrow, I'd spend today with you.",
    "You're not just my love story - you're my favorite story.",
  ],
  Bollywood: [
    "Tujhe dekha toh ye jaana sanam... pyar hota hai deewana sanam!",
    "Tu cheese badi hai mast mast... I mean, you're absolutely amazing!",
    "Jab se tere naina mere nainon se lage... neend na aaye, chain na aaye!",
    "Pehla nasha, pehla khumar... that's what seeing you feels like!",
    "Are you from Dilwale? Because you stole my Dulhania heart!",
    "Main agar kahoon tumsa haseen... qayanat mein nahi hai! (And I really mean it)",
    "Kuch kuch hota hai... tum nahi samjhoge! But seriously, my heart skips beats around you.",
    "Ek ladki ko dekha toh aisa laga... jaisi khilta gulab! That ladki is you.",
    "Tu meri complete life hai... not a semicolon, a full stop!",
    "Yeh bandhan toh pyar ka bandhan hai... wait, too soon? Let me start with coffee first.",
    "Are you Simran? Because I've been running through mustard fields looking for you!",
    "Tere bina zindagi se koi shikwa nahi... but WITH you, life would be next level!",
    "Like Raj said to Simran: Ja Simran ja, jee le apni zindagi... but please come back to me!",
    "Mere khwabon mein jo aaye... I think that's you! No filter needed.",
    "Dil ne jise apna kaha... that's you, in case my staring wasn't obvious enough.",
    "Chaiyya chaiyya... I'd dance on a train for you. Okay, maybe not a moving train.",
    "You're like a Bollywood movie - dramatic, beautiful, and I can't look away!",
    "Meri umar ke naujawan dillon ko... you've basically hacked, congratulations!",
    "Tum hi ho... my Aashiqui, my everything! Sorry, got carried away.",
    "Are you a Shah Rukh Khan movie? Because I want to watch you on repeat forever!",
    "Main hoon na! Whatever you need, I'm here. That's my pickup line AND my promise.",
    "Teri meri, meri teri... prem kahani hai mushkil. But let's start it anyway?",
    "You make me feel like a Bollywood hero in the rain... dramatic and slightly wet.",
    "Tujhe kitna chahne lage hum... isme koi doubt nahi! None at all.",
    "Like Devdas, I could be tragic without you. But let's go for a happy ending instead!",
    "Kabhi kabhi mere dil mein khayal aata hai... ki tum hi ho meri destiny!",
    "You must be a Bollywood song because you're stuck in my head 24/7!",
    "Humko humise chura lo... dil mein kahin tum chhupa lo! But like, in a non-creepy way.",
    "Ishq wala love hai yeh! I know because my heart goes dhak dhak when I see you.",
    "Tere liye hum hain jiye... horton ne yeh jaana! You are my everything.",
    "Are you Kajol? Because my heart does the DDLJ thing every time I see you.",
    "You're like Geet from Jab We Met - full of life and impossible not to love!",
    "Abhi mujh mein kahin... baaki thodi si hai zindagi. You complete the rest!",
    "Tu jaane na... but I'll tell you anyway: I really like you!",
    "Like Munna Bhai's jaadu ki jhappi, your smile is magic!",
    "Ye ishq hai... ye ishq hai! Sorry, I break into songs around beautiful people.",
    "Hum tum ek kamre mein band ho... for coffee! Just coffee! I meant coffee!",
    "Tum se hi... din hota hai, surmayi shaam hoti hai. You light up my world!",
    "Are you a Bollywood interval? Because I need a break after seeing your beauty.",
    "My love for you is like a Karan Johar film - over the top and full of emotion!",
    "Like Shah Rukh with his arms open... I'm just standing here, waiting for you!",
    "Zara zara behekta hai... mehekta hai. That's me around you - totally lost!",
    "You're like a superhit Bollywood movie - everyone wants to watch, but I want a private screening!",
    "Dil to pagal hai... literally, my heart goes crazy for you!",
    "Kuch to hua hai, kuch ho gaya hai... basically, I'm falling for you. Hard.",
    "Are you the Taj Mahal? Because I'd build an empire of love for you!",
    "Tumhi dekho naa... how can I NOT stare at perfection?",
    "Like a Hindi serial, my love for you has no end. But way less dramatic. Okay, maybe equally dramatic.",
    "Janam janam saath chalna... I'm booking tickets for all seven lifetimes!",
    "You give me that Ranbir-Deepika chemistry vibe. Let's make our own blockbuster!",
    "Bade bade deshon mein aisi chhoti chhoti baatein hoti rehti hain... and meeting you is the best one!",
  ],
};

export default function AiPickupLineGenerator() {
  const [style, setStyle] = useState<Style>("Cheesy");
  const [results, setResults] = useState<string[]>([]);
  const [copiedIdx, setCopiedIdx] = useState<number | null>(null);
  const [seed, setSeed] = useState(0);

  const generate = () => {
    const pool = lines[style];
    const shuffled = [...pool].sort(() => Math.sin(seed * 9301 + 49297) - 0.5);
    setResults(shuffled.slice(0, 10));
    setSeed((p) => p + 1);
  };

  const copy = (idx: number) => {
    navigator.clipboard?.writeText(results[idx]);
    setCopiedIdx(idx);
    setTimeout(() => setCopiedIdx(null), 2000);
  };

  const styles: Style[] = ["Cheesy", "Smooth", "Nerdy", "Funny", "Romantic", "Bollywood"];

  return (
    <div className="space-y-6">
      <div>
        <label className="text-sm font-semibold text-gray-700 block mb-2">Style</label>
        <div className="flex gap-2 flex-wrap">
          {styles.map((s) => (
            <button key={s} onClick={() => setStyle(s)} className={s === style ? "btn-primary" : "btn-secondary"}>{s}</button>
          ))}
        </div>
      </div>
      <div className="flex gap-3 flex-wrap">
        <button onClick={generate} className="btn-primary">Generate Pickup Lines</button>
        {results.length > 0 && (
          <button onClick={generate} className="btn-secondary">Regenerate</button>
        )}
      </div>
      {results.length > 0 && (
        <div className="space-y-3">
          {results.map((line, i) => (
            <div key={i} className="result-card flex justify-between items-start gap-3">
              <div className="flex gap-3 items-start">
                <span className="text-sm font-bold text-indigo-500 mt-0.5">{i + 1}.</span>
                <p className="text-gray-800 leading-relaxed">{line}</p>
              </div>
              <button onClick={() => copy(i)} className="text-xs text-indigo-600 font-medium hover:underline whitespace-nowrap">{copiedIdx === i ? "Copied!" : "Copy"}</button>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
